### DISCUSSION TITLE
Auto generate env config from yaml

### DISCUSSION THREAD

**Discussion by jackmac92** [redpanda-data/connect#1008] [Ideas]
Looking to deploy with docker, and env var configuration seems easiest to manage for that. But I'd like to still write my config in yml, and have CI generate the correct env vars. 

Since the env vars largely appear to be the same structure as the yaml, the below jq script gets me most of the way
````
cat benthos-conf.yml| yq | jq '. as $root |\n path(..) | . as $path |\n $root | getpath($path) as $value |\n select($value | scalars) |\n "\([$path[]] | join("_") | ascii_upcase)=\($value)"\n ' -r
````

But I noticed some env vars do not "map" from their yaml definitions, e.g. `buffer:` options are much different.

Any thoughts about supporting the above jq script, and ensuring the env var configuration can be generated by mapping yaml defs to env vars?

e.g. 

````yaml
input:
  http_server:
    path: /post
    ws_path: /post/ws
    allowed_verbs:
      - POST
    timeout: 5s
    rate_limit: ""
````
generates
````
INPUT_HTTP_SERVER_PATH=/post
INPUT_HTTP_SERVER_WS_PATH=/post/ws
INPUT_HTTP_SERVER_ALLOWED_VERBS_0=POST
INPUT_HTTP_SERVER_TIMEOUT=5s
INPUT_HTTP_SERVER_RATE_LIMIT=
````
(I know slight issue with array values getting suffixes, will find a fix for that if this could be supported)
