### DISCUSSION TITLE
Hang on Windows

### DISCUSSION THREAD

**Discussion by rdilipk** [redpanda-data/connect#1159] [Q&A]
I have been playing around with benthos with simple input/output mappings. I am experiencing some weird problems when I run it on Windows. A simple mapping to read from stdin, massage the output and print to stdout (from the walkthrough section) takes almost _5 minutes_ for the application to output any value. Sometimes (~20% of the time) it displays the output quickly. The rest of the time it almost takes the same amount of time: around 5min 50+ seconds but < 6 minutes. Almost feels like it's deliberately waiting for a specified time interval before printing the output. Anybody has seen something like this before? The command line I run is fairly straight forward:

C:/> my_app_that_writes_to_stdout.exe | benthos.exe -c ./myconfig.yaml

I am running this on Windows 10 Enterprise.

**Comment by Jeffail** [comment]
Hey @rdilipk can you paste the full config you're running?

**Reply by rdilipk** [reply]
Sure. It's almost an exact replica of stuff I found in your excellent docs:

```
input:
  stdin: {}

pipeline:
  processors:
    - resource: foo_proc # Processor that might fail
    - catch:
      - log:
          message: "Processing failed due to: ${!error()}"

processor_resources:
  - label: foo_proc
    bloblang: |
      root = content().decode("hex").parse_json()

output:
  stdout: {}
```
