### DISCUSSION TITLE
`<` and `>` symbols replaced by their unicode codepoint values

### DISCUSSION THREAD

**Discussion by rdilipk** [redpanda-data/connect#1244] [Q&A] [answered]
I have a `sql_insert` processor that inserts a JSON document into a table (postgres) with a column of type `json`. I find that all the `<` and `>` characters replaced by `\u003c` and `\u003e`  respectively. I don't see this problem if such documents are inserted into postgres by any other means and I don't think JSON itself requires any such transformation. Is this a known issue?

**Comment by rdilipk** [comment, marked as answer]
This seems like the way `json.Marshal` works in Go. Unmarshalling gets rid of it. So never mind.

**Reply by mihaitodor** [reply]
Hey @rdilipk, I missed this discussion when you started it, sorry about that! There is an option in Go to disable this particular character escaping and we do use it [here](https://github.com/benthosdev/benthos/blob/5204102d3e18353e1d4952aaeab56efb93b71188/internal/message/part.go#L145). However, depending on your pipeline, you might go through a different path in the code which doesn't set this option.

For example, given the following table in Postgres:
```sql
CREATE TABLE demo(id SERIAL PRIMARY KEY, DATA JSON)
```

and the following Benthos config:
```yaml
input:
  generate:
    mapping: 'root = {"foo": "<bar>"}'
    interval: 1s

output:
  sql_insert:
    driver: "postgres"
    dsn: "postgresql://localhost:5432/mihaitodor?sslmode=disable"
    table: "demo"
    columns: ["DATA"]
    args_mapping: "root = [ content() ]"
    # args_mapping: "root = [ json().string() ]"
```

I get the following data in the table:

```
> select * from demo;
+----+-----------------+
| id | data            |
|----+-----------------|
| 25 | {"foo":"<bar>"} |
| 26 | {"foo":"<bar>"} |
| 27 | {"foo":"<bar>"} |
+----+-----------------+
SELECT 3
Time: 0.006s
```

However, if I set `args_mapping` to `root = [ json().string() ]`, then I get the following data:

```
select * from demo;
+----+---------------------------+
| id | data                      |
|----+---------------------------|
| 35 | {"foo":"\u003cbar\u003e"} |
| 36 | {"foo":"\u003cbar\u003e"} |
| 37 | {"foo":"\u003cbar\u003e"} |
+----+---------------------------+
SELECT 3
Time: 0.006s
```

The difference is that the Bloblang [`string()`](https://www.benthos.dev/docs/guides/bloblang/methods#string) method doesn't use `SetEscapeHTML(false)` when serialising the JSON string, because, for objects, it [calls](https://github.com/benthosdev/benthos/blob/8eff8ca5ccf7cb4b6fdee7af6e67c070bebe3073/internal/bloblang/query/type_helpers.go#L336) `gabs.Wrap(i).String()`, which marshals the data [here](https://github.com/Jeffail/gabs/blob/280654410ea84ee0ef9a40fb73155233b66badf5/gabs.go#L786-L791).

I'm not sure why this character escaping is the default behaviour of the Go JSON marshaller, but I wonder if maybe the `string()` method should disable it or maybe provide a parameter that lets users control it. @Jeffail WDYT?
