### DISCUSSION TITLE
google pubsub to google bq not working

### DISCUSSION THREAD

**Discussion by mittal-jatin** [redpanda-data/connect#1296] [Q&A]
Hi, I am using benthos to stream data from google pubsub to google bigQuery using the below `config.yaml` :
```
input:
  label: my_input_label
  gcp_pubsub:
    project: "my_project_name"
    subscription: "my_subscription_name"
    sync: false
pipeline:
  processors:
    - log:
        level: INFO
        message: Hello World
output:
  label: my_output_label
  gcp_bigquery:
    project: "my_project_name"
    dataset: "dataset_name"
    table: "table_name"
    format: NEWLINE_DELIMITED_JSON
    max_in_flight: 10000
    write_disposition: WRITE_APPEND
    batching:
      count: 10000
      period: 10s

```
In documentation, I could not differentiate between `max_in_flight` and `batching.count` clearly. Can someone give more context on these two fields. Also, when I tried changing `max_in_flight` value to 10000 and `batching.count` to 1000, I was getting some messages in BQ but not all. 
For the above configurations, I can see the `Hello World` logs in terminal but on pubsub console 9000 messages are unacknowledged and there is only 1000 records in BQ.
Can someone tell where am I missing ? 
Using benthos version - 4.0.0
