### DISCUSSION TITLE
Will try catch with branch

### DISCUSSION THREAD

**Discussion by smalljimmy** [redpanda-data/connect#1336] [Q&A]
Suppose I have following pipeline definition.

Will catch block be executed when test_processor fails?

```
pipeline:
  processors:
        - try:
          - branch:
              request_map: |
                root = this
              processors:
                - resource: test_processor
              result_map: |
                root.verified = this
        - catch:
          - bloblang: |
              root.meta.error = error()
              root.status = 400
```

**Comment by mihaitodor** [comment]
Yep! But don't trust me and try it out yourself.

```yaml
input:
  generate:
    mapping: |
      root = {}
    interval: 0s
    count: 1

pipeline:
  processors:
    - try:
        - branch:
            request_map: |
              root = this
            processors:
              - bloblang: |
                  throw("kaboom!")
            result_map: |
              root.verified = this

        - log:
            message: "The rest of the processors in `try` won't get executed"

    - catch:
        - bloblang: |
            root.meta.error = error()
            root.status = 400

    - log:
        message: "The catch processor clears the error: ${! error() }"

output:
  stdout:
    codec: lines
```

**Reply by pokstad** [reply]
When I try this pipeline, it still logs the kaboom error even though the branch is wrapped with a try. Is that expected? I would expect that any try or catch logic would suppress normal error logging and let me choose how to surface the exception. Is there a way to suppress errors like kaboom?

**Reply by mihaitodor** [reply]
Yep, that's by design. You shouldn't perform work through exceptions by using the `throw` keyword to change behaviour and this log indicates a bug in your code that you need to fix. Ideally, pure processors which don't perform any IO should never fail. Instead, they should set some metadata or some field which indicates that the happy flow can't be performed and it's up to the subsequent processors to pick that up and handle it appropriately. For processors with side-effects, things can always go wrong, but we want to make sure that users are aware when that happens. In some cases, it might be desirable to suppress logging for certain components, but that would require an enhancements on a case-by-case basis.

**Comment by smalljimmy** [comment]
Thank you. In my case, the test_processor is a HTTP processor

```
  - label: test_processor
    http:
      url: 'http://api:8000/v2.0/private/verify_preapply'
      verb: PUT
      headers:
        Content-Type: application/json
        X-Product-Blacklist: '${! meta("X-Product-Blacklist")}'
      timeout: 20s
```
      
  And I notice the catch blocker is NOT executed if the http call failed with 500 error. Is there a way to capture such error using try..catch?
