### DISCUSSION TITLE
Controlling the prefetch/batch count on redis_list input

### DISCUSSION THREAD

**Discussion by sarnikowski** [redpanda-data/connect#1451] [Q&A] [answered]
Hello

First of all, thanks for a really great tool!
I am trying to control what I assume is a prefetch count for a `redis_list` input. I've dug a bit into the codebase/documentation, and I believe the behavior I am observing has something to do with batching. Consider the following configuration:
```yaml
input:
  broker:
    copies: 1
    inputs:

      - label: "processing_queue"
        redis_list:
          url: "redis://:${QUEUE_PASSWORD}@${QUEUE_URI}"
          key: ${QUEUE_NAME}
          timeout: 5s

        processors:
          - bloblang: |
              meta object_key = this.key
          - log:
              level: INFO
              message: "Queue item"
              fields_mapping: |
                root.meta = meta()

      - http_server:
          address: "0.0.0.0:3333"
          path: /foo
          ws_path: /foo/ws
          allowed_verbs:
            - POST
          timeout: 900m
          sync_response:
            status: ${! meta("status") | 200 }
            metadata_headers:
              include_patterns:
                - .*

pipeline:
  threads: 1
  processors:
    - sleep:
        duration: 5s
    - log:
        level: INFO
        message: "Proccessed item"
        fields_mapping: |
          root.meta = meta("object_key")
```
If i run this on a redis list, in which I have placed 4 items, I get the following output:
```
{"@service":"benthos","label":"","level":"info","meta":"KEY-1","msg":"Queue item","path":"root.input.processors.1","time":"2022-09-20T08:37:55Z"}
{"@service":"benthos","label":"","level":"info","meta":"KEY-2","msg":"Queue item","path":"root.input.processors.1","time":"2022-09-20T08:37:55Z"}
{"@service":"benthos","label":"","level":"info","meta":"KEY-1","msg":"Proccessed item","path":"root.pipeline.processors.1","time":"2022-09-20T08:38:00Z"}
{"key":"KEY-1"}
{"@service":"benthos","label":"","level":"info","meta":"KEY-3","msg":"Queue item","path":"root.input.processors.1","time":"2022-09-20T08:38:00Z"}
{"@service":"benthos","label":"","level":"info","meta":"KEY-2","msg":"Proccessed item","path":"root.pipeline.processors.1","time":"2022-09-20T08:38:05Z"}
{"key":"KEY-2"}
{"@service":"benthos","label":"","level":"info","meta":"KEY-4","msg":"Queue item","path":"root.input.processors.1","time":"2022-09-20T08:38:05Z"}
{"@service":"benthos","label":"","level":"info","meta":"KEY-3","msg":"Proccessed item","path":"root.pipeline.processors.1","time":"2022-09-20T08:38:10Z"}
{"key":"KEY-3"}
{"@service":"benthos","label":"","level":"info","meta":"KEY-4","msg":"Proccessed item","path":"root.pipeline.processors.1","time":"2022-09-20T08:38:15Z"}
{"key":"KEY-4"}
```

If i query redis right after I start this, it shows that 3 of the keys have been popped off the list. Even though the input processor only shows 2 log outputs. Specifically, I am interested in controlling the prefetch count. I would like this prefetch count to be 1, which means that Benthos should pop a single item and wait with popping the next until the first item has finished processing (including being outputted). I have tried with adjusting the batch count on the broker but to no avail. So my question is, is this possible ?
Thanks a bunch in advance !

**Comment by mihaitodor** [comment]
Hey @sarnikowski, I could be wrong, but I believe this greedy behaviour that you're seeing can't be adjusted right now... Would you mind opening an issue describing in which scenario people might benefit from such lazy reading from the input?

As a workaround, I believe the following might do the trick, but it's a terrible, terrible hack and I don't think anyone should use it in production (tested with Kafka which you can substitute with your broker input):

```yaml
input:
  read_until:
    input:
      read_until:
        input:
          kafka:
            addresses:
              - localhost:9092
            topics:
              - test
            consumer_group: foogroup
            start_from_oldest: true
        check: true
        restart_input: false
    check: false
    restart_input: true

  processors:
    - log:
        message: ${! count("input") }

pipeline:
  threads: 1
  processors:
    - sleep:
        duration: 2s

output:
  stdout: {}
```
