### DISCUSSION TITLE
http_client URL + headers dynamic values with interpolation

### DISCUSSION THREAD

**Discussion by elukey** [redpanda-data/connect#1506] [Q&A] [answered]
Hi everybody!

I am currently testing Benthos with a simple config:

```
input:
  broker:
    inputs:
      - kafka:
          addresses:
          - some-kafka-broker:port
          tls:
             [..]
          topics: [ some-topic ]
          consumer_group: elukey-benthos-test
  label: "kafka"
buffer:
  none: {}
pipeline:
  threads: 1
  processors:
  - bloblang: |
      root = if this.database != "enwiki" {
        deleted()
      } else {
        { "revision_create_event":  this }
      }
output:
  label: ""
  http_client:
    url: "https://some_domain:30443/v1/models/"${! this.revision_create_event.database }"-goodfaith:predict"
    verb: POST
    headers:
      "Host": ${! this.revision_create_event.database }"-rest-of-the-hostname"
    tls:
       [...]
    rate_limit: http_client_output
    timeout: 30s
    retry_period: 30s
```

Basically I consume json messages from kafka, wrap them in a custom json format (basically a dict with key "revision_create_event" and value the whole json message) and then I'd like to hit a certain HTTP endpoint, using a value inside the message as part of the URL and Host header. I tried multiple configurations but so far no luck. Any suggestion about how to do it?

**Comment by elukey** [comment, marked as answer]
Found a way to do it:

```
  http_client:
    url: 'https://some-domain:30443/v1/models/${! json("revision_create_event.database") }-goodfaith:predict'
    verb: POST
    headers:
      "Host": '${! json("revision_create_event.database") }--rest-of-the-hostname'
```

Single quotes are important IIUC.
