### DISCUSSION TITLE
Modify http_client response

### DISCUSSION THREAD

**Discussion by nuno-al** [redpanda-data/connect#1627] [Q&A] [answered]
Hi,

If I have a http_client output, is it possible to modify the response before returning it to the caller?

For example, in the following config, can I add a processor after the propagate_response so I can mutate the http_client response before returning it?

```
input:
  http_server:
    path: /post
output:
  http_client:
    url: http://localhost:4196/post
    verb: POST
    propagate_response: true
```
