### DISCUSSION TITLE
Environment variables in tests

### DISCUSSION THREAD

**Discussion by nevesb** [redpanda-data/connect#1924] [Q&A]
Hello, I started using bethos a while ago and now I'm passing some parameters through environment variables. So for example I have this code snippet in my config:
```yaml
input:
  http_client:
    url: ${my_url_with_token}
    verb: GET
```

When I run my tests now the following error message appears:

```
Test 'config.yaml' failed

Failures:

--- config.yaml ---

Lint: (1,1) required environment variables were not set: [my_url_with_token]
```

I tried to run configure my environment variable in several ways, for example:

```yaml
tests:
  - name: input tokens
    target_processors: '/input/processors'
    environment:
        my_url_with_token: http://dummyurl.com/
```

But no way i put it, it accepts my variable. I think I'm using this field incorrectly. How should I put this?

**Comment by Jeffail** [comment]
Hey @nevesb, which version of Benthos are you running? It's possible that this has been fixed as I've tried to reproduce it and it's working as intended, put an example up here: https://github.com/benthosdev/benthos/blob/main/config/test/env_var_stuff.yaml

**Reply by nevesb** [reply]
I'm using github.com/benthosdev/benthos/v4 v4.14.0

**Reply by mihaitodor** [reply]
Seems to reproduce with the following in Benthos v4.15.0 (but I think it's a bit contrived, since I guess the specified env vars only apply to the processors?):

```yaml
input:
  http_client:
    url: ${my_url_with_token}
    verb: GET
  processors:
    - noop: {}

tests:
  - name: input tokens
    target_processors: '/input/processors'
    environment:
        my_url_with_token: http://dummyurl.com/
```

```
> benthos test conf.yaml
Test 'conf.yaml' failed

Failures:

--- conf.yaml ---

Lint: (1,1) required environment variables were not set: [my_url_with_token]
```

**Reply by nevesb** [reply]
Same issue at v4.15.0

**Comment by Jeffail** [comment]
Whoops, thanks for the feedback, I missed that it was the linting step before tests being applied causing it. I've disabled env var interpolation checks for unit tests: https://github.com/benthosdev/benthos/commit/e62bceb8792662f4f72a7462a3c2627c0946298a

**Comment by andrevmatos** [comment]
This still fails, if the variable is used somewhere in template where its absence would cause a wrong template.
e.g.
```yaml
input:
  http_client:
    url: ${my_url_with_token}
    verb: GET
  processors:
    - mapping: |
        root = {"id": ${MYID}}

tests:
  - name: input tokens
    target_processors: '/input/processors'
    environment:
      my_url_with_token: http://dummyurl.com/
      MYID: 123
```
```sh
$ benthos test ./test.yaml
Test 'test.yaml' failed

Failures:
--- test.yaml ---
Lint: (8,31) expected query, got: }
exit status 1
```
```sh
$ MYID=123 benthos test ./test.yaml
Test 'test.yaml' succeeded
```
