### DISCUSSION TITLE
http processor Bearer Authentication support

### DISCUSSION THREAD

**Discussion by ppawelzak** [redpanda-data/connect#2087] [Q&A]
Hi, could you please add Bearer Authentication support to [http processor](https://www.benthos.dev/docs/components/processors/http/)?

**Comment by mihaitodor** [comment]
@ppawelzak Not sure what you're looking for, but I believe that already works:
```yaml
- http:
     ...
     headers:
       Authorization: "Bearer <your token>"
```

LE: Also migrated this to a discussion as mentioned in #2026.
