### DISCUSSION TITLE
Read txt files and get MySQL data

### DISCUSSION THREAD

**Discussion by mapplechannel** [redpanda-data/connect#2105] [General]
1.Hello, when I read the txt file, I found that the read data was not in json format and could not be operated on. My yaml is：
input:
  label: ""
  sftp:
    address: "127.0.0.1:22"
    credentials:
      username: "admin"
      password: "123456"
      private_key_file: ""
      private_key_pass: ""
    paths: [/home/sftp_root/shared/123.txt]
    codec: all-bytes
    watcher:
      enabled: false
      minimum_age: 1s
      poll_interval: 1s
      cache: ""
      
pipeline:
  processors: []
    
output:
  label: ""
  stdout:
    codec: lines

Please tell me how I should configure it so that the txt content can be turned into a json format data，thanks

2.Another question is that when I read the int value of MySQL, I found that the obtained data became string type. How can I keep the data type unchanged, which is int?

**Comment by Jeffail** [comment]
Converting to a discussion as per: https://github.com/benthosdev/benthos/issues/2026

**Comment by mihaitodor** [comment]
> Please tell me how I should configure it so that the txt content can be turned into a json format data，thanks

Does the text in `/home/sftp_root/shared/123.txt` contain a single valid JSON object? This works for me:

```
{
  "foo": "bar"
}
```

```yaml
input:
  file:
    paths:
      - ./foo.txt
    codec: all-bytes

  processors:
    - log:
        message: ${! json("foo") }

output:
  stdout: {}
```

Output:

```
INFO Running main config from specified file       @service=benthos path=test.yaml
INFO Listening for HTTP requests at: http://0.0.0.0:4195  @service=benthos
INFO Consuming from file './foo.txt'               @service=benthos label="" path=root.input
INFO Launching a benthos instance, use CTRL+C to close  @service=benthos
INFO bar                                           @service=benthos label="" path=root.input.processors.0
{
  "foo": "bar"
}
INFO Pipeline has terminated. Shutting down the service  @service=benthos
```

Note the line with "INFO bar ..." which was emitted by the `log` processor.

> Another question is that when I read the int value of MySQL, I found that the obtained data became string type. How can I keep the data type unchanged, which is int?

Looks like that's a limitation of the underlying MySQL client library (YUCK!!!): https://github.com/go-sql-driver/mysql/issues/407#issuecomment-172583652 and https://github.com/go-sql-driver/mysql/issues/861

You can hack around it by using the `sql_raw` input (or processor) and forcing a prepared statement like so (feel free to use any other SQL query which has at least one placeholder (`?`) in it):

```yaml
input:
  sql_raw:
    driver: mysql
    dsn: testuser:testpass@tcp(localhost:3306)/testdb?multiStatements=true
    query: "SELECT FOO, BAR FROM TEST WHERE 1 = ?"
    args_mapping: |
      root = [
        1
      ]
    init_statement: CREATE TABLE IF NOT EXISTS TEST (FOO INT, BAR BOOLEAN); INSERT INTO TEST (FOO, BAR) VALUES (666, 0), (42, 1);

  processors:
    - mutation: |
        root.BAR = this.BAR == 1

output:
  stdout: {}
```

Since you also asked about booleans in #2108, as you can see from [this conversation](https://github.com/go-sql-driver/mysql/issues/440), you'll need to do the conversion manually on the Benthos side, which is why I added that `mutation` processor.
