### DISCUSSION TITLE
Additional parameters for Kafka input

### DISCUSSION THREAD

**Discussion by ppavlov39** [redpanda-data/connect#2243] [Q&A]
Hello!
We were experiencing a strange stop in processing messages from Kafka ([using kafka input](https://www.benthos.dev/docs/components/inputs/kafka)). There are 12 partitions in the topic and we launch 12 pods to read them, but almost immediately most of the pods stop processing anything.
We use an http client as output. Both Kafka input and HTTP output use batch processing (batch size is 2000).
The complete configuration of these components is shown below.
We have a hypothesis that changing some timeouts in the Kafka consumer ([sarama](https://github.com/IBM/sarama)) can help us.
Is there a way to configure settings that Kafka input doesn't have?

```yaml
input:
kafka:
      addresses: <>
      topics: <>
      consumer_group: <>
      client_id: <>
      checkpoint_limit: 1
      target_version": "2.4.0"
      max_processing_period: "300ms"
      group.heartbeat_interval: "10s"
      batching: 
        count: 2000
        period: 120s
```

```yaml
output:
http_client: 
          url: <>
          verb: "POST"
          rate_limit: ""
          timeout: "120s"
          headers:
            Content-Type": "application/json"
            Content-Encoding": "gzip"
            ...
          max_in_flight: 1
          batching: 
            count: 2000
            period: 120s
            processor": 
              archive:
                  format: lines
              compress:
                  algorithm: gzip
                  level: 5
```
