### DISCUSSION TITLE
Issue with Establishing Elasticsearch Connection with SSL as an Output

### DISCUSSION THREAD

**Discussion by aliSadegh** [redpanda-data/connect#2281] [Q&A] [answered]
Hello everyone,

I'm currently working on connecting to Elasticsearch as an output in Benthos. However, I'm facing an issue with the following error:

```
level=error msg="Failed to connect to Elasticsearch: no active connection found: no Elasticsearch node available" @service=benthos label="" path=root.output
```

Initially, when I tested my scenario without SSL on the Elasticsearch cluster, everything worked fine. However, after enabling SSL on the cluster, I received the following error:

```
level=error msg="Failed to connect to Elasticsearch: health check timeout: Head \"https://es01:9200\": tls: failed to verify certificate: x509: certificate signed by unknown authority: no Elasticsearch node available" @service=benthos label="" path=root.output
```

Upon enabling TLS and setting `skip_cert_verity=true`, I encountered the current error.

My config.yaml:
```
input:
    label: "input_test"
    generate:
        mapping: |
            root = {"name":"test","host":random_int(seed:timestamp_unix_nano(),min:1,max:3)}
        batch_size: 100
        interval: 10s

pipeline:
    processors:
        - group_by_value:
            value: ${! json("host")}

output:
  elasticsearch:
    urls:
        - https://es01:9200
    index: 'datastream_test_${! json("host")}'
    healthcheck: true
    tls:
      enabled: true
      skip_cert_verify: true
      enable_renegotiation: false
    basic_auth:
        enabled: true
        username: "elastic"
        password: "123456"
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
```
 I would appreciate any assistance in resolving this issue.
Thank you.
