### DISCUSSION TITLE
Is there a programmatic way to bring up benthos in an already existing app

### DISCUSSION THREAD

**Discussion by ghstahl** [redpanda-data/connect#2287] [General]
My existing app has a cli and it doesn't look like its compatible with benthos.  Here is my little hack in my main, but I would like more of something like.

```go
benthosInstance := service.New(options)
benthosInstance.Start()

//much later
benthosInstance.Stop()
```

## My Hack
```go

	originalArgs := os.Args

	// cancel context
	ctx, cancel := context.WithCancel(ctx)
	// benthos thinks its the only one, so lets replace the args and then set them back when it launches.
	benthosOSArgsS := os.Getenv("BENTHOS_OS_ARGS")
	fmt.Println("BENTHOS_OS_ARGS", benthosOSArgsS)
	// split them
	benthosOSArgs := strings.Split(benthosOSArgsS, ",")
	os.Args = []string{
		originalArgs[0],
	}
	os.Args = append(os.Args, benthosOSArgs...)
	log.Info().Interface("os.Args", os.Args).Msg("os.Args")
	os.Args[0] = "benthos"
	go func() {
		service.RunCLI(context.Background())
	}()
	time.Sleep(5 * time.Second)
	os.Args = originalArgs
```

**Comment by mihaitodor** [comment]
Hey @ghstahl, I'm not sure if that `os.Args` hack does what you expect it to, since Go doesn't seem to expose a mechanism to overwrite it globally, but I could be wrong. See [here](https://groups.google.com/g/golang-nuts/c/rG6xShds2Dc) and [here](https://gist.github.com/klingtnet/01f8ee62ec19d926ac57389d3372314a).

I think you're looking for the `github.com/benthosdev/benthos/v4/public/service/servicetest` package which provides [`RunCLIWithArgs()`](https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.24.0/public/service/servicetest#RunCLIWithArgs).

**Reply by ghstahl** [reply]
BTW: Go does let you swap out the args.  The problem is that a service like benthos may use them much later and crash because I swapped them back after I sleep for 5 seconds.  My hack is very bad form.

It does look like RunCLIWithArgs() is my answer.
```go
         ctx, cancel := context.WithCancel(ctx)
	benthosOSArgsS := os.Getenv("BENTHOS_OS_ARGS")
	fmt.Println("BENTHOS_OS_ARGS", benthosOSArgsS)
	// split them
	benthosOSArgs := strings.Split(benthosOSArgsS, ",")

	newArgs := []string{
		"benthos",
	}
	newArgs = append(newArgs, benthosOSArgs...)
	log.Info().Interface("benthos_args", newArgs).Msg("benthosOSArgs")

	go func() {
		servicetest.RunCLIWithArgs(ctx, newArgs...)
	}()
```

A follow-up.  Can I have multiple benthos instances in my app?  i.e. a couple of go routines each with their own isolated benthoses?

**Reply by mihaitodor** [reply]
> Can I have multiple benthos instances in my app? i.e. a couple of go routines each with their own isolated benthoses?

Yep! You’ll want to look at [Streams Mode](https://www.benthos.dev/docs/guides/streams_mode/about). Also, note there are [StreamBuilder API examples](https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.24.0/public/service#example-package-StreamBuilderMultipleStreams) on how to launch streams directly.

**Reply by ghstahl** [reply]
Would you consider moving that ```RunCLIWithArgs``` api out of the test area as this is used as a production api for me.

**Reply by mihaitodor** [reply]
It's a stable API which won't change. Besides that, I'll have to let others chime in, since I didn't design it.

**Reply by ghstahl** [reply]
BTW: It looks like the ```StreamBuilder``` is the real answer.  Noice!

This is exactly what I want.
```go
streamOne, err := builderOne.Build()
panicOnErr(err)
go func() {
  defer wg.Done()
  panicOnErr(streamOne.Run(context.Background()))
}()
// much later
streamOne.Stop(context.Background())
```

**Reply by ghstahl** [reply]
Got a problem.
this is my kafka.yml
```
http:
  enabled: false
input:
  kafka:
    addresses: ["${INPUT_KAFKA_BROKERS}"]
    topics: ["cloudevents-core"]
    consumer_group: "$Default2"
    multi_header: true
    batching:
      count: 3
      period: 20s
      processors:
        - json_schema:
            schema_path: "file://C:/work/mapped/benthos-cloudevents-fluffycore/config/benthos/request_units_schema.json"
        - switch:
            - check: errored()
              processors:
                - for_each:
                    - while:
                        at_least_once: true
                        max_loops: 0
                        check: errored()
                        processors:
                          - catch: [] # Wipe any previous error
                          - mapping: "deadletterit(@,content())"
                - mapping: |
                    deleted()

        - archive:
            format: binary

pipeline:
  threads: 1
  processors:
    - sleep:
        duration: 1s

output:
  cloudevents_grpc:
    grpc_url: "${OUTPUT_CLOUDEVENTOUTPUT_GRPC_URL}"
    max_in_flight: 64
    channel: "mychannel"

    # auth[optional] one of: [oauth2,basic,apikey](ordered by priority)
    #--------------------------------------------------------------------
    #auth:
    #  basic:
    #    user_name: "admin"
    #    password: "password"
    #  oauth2:
    #    client_id: "my_client_id"
    #    client_secret: "secret"
    #    token_endpoint: "https://example.com/oauth2/token"
    #    scopes: ["scope1", "scope2"]
    #  apikey:
    #    name: "x-api-key"
    #    value: "secret"
logger:
  level: ${LOG_LEVEL}
  format: json
  add_timestamp: true
  static_fields:
    "@service": benthos

```

It loads find when passed to the cli.
```
-c ./kafka.yaml
``` 

doesn't get parsed by the yaml parser when I load it and pass it.
```go
func LoadYamlFile(filename string) (string, error) {
	// load kafka.yml into a string
	kafkaYaml, err := os.ReadFile(filename)
	if err != nil {
		return "", err
	}
	return string(kafkaYaml), nil
}

kafkaYaml, err := LoadYamlFile("./kafka.yaml")
if err != nil {
	log.Fatal().Err(err).Msg("Error reading file")
}

builderOne := benthos_service.NewStreamBuilder()
err = builderOne.SetYAML(kafkaYaml)
if err != nil {
  log.Error().Err(err).Msg("Error reading file")
}
```

error log"
```
4:09PM ERR main.go:76 > Error SetYAML error="lint errors: (25,51) expected whitespace, got: (@,co\n(39,1) unable to infer component type"
```
Doesn't like my custom func.
```
- mapping: "deadletterit(@,content())"
```
I haven't gone down the CLI path yet to see why its loaded differently.
