### DISCUSSION TITLE
Unable to delete message from branch

### DISCUSSION THREAD

**Discussion by mariamjamal94** [redpanda-data/connect#2300] [Q&A]
I am using benthos for the first time and am miserably stuck. 
My problem is that in case an `http` processor 'errors' (e.g. 500 response), I delete the root in `catch` mapping i.e. `root = deleted()`
While unit testing this behavior, I expect the output batches to be empty. However it fails, expecting the output batch to be the same as the input batch.

Processor:
 ```
    - label: "rule_engine_request"
      branch:
        request_map: |
          root = {"test1": "test1"}
          root = if meta("validation_error").not_null().catch("") != "" {
            deleted()
          }
        processors:
          - log:
              level: INFO
              message: "Sending request to rule engine: ${!this}"
          - label: "make_rule_engine_http_request"
            http:
              url: http://httpbin.org/status/500
              verb: POST
              headers:
                Authorization: "Bearer ${RULE_ENGINE_TOKEN}"
              successful_on:
                - 200
              drop_on:
                - 404
                - 500
                - 502
                - 503
          - catch:
              - log:
                  message: "Rule engine request failed unexpectedly with code ${! meta(\"http_status_code\")}"
              - mapping: root = deleted()
        result_map: root = this
```

My unit test is very simple:
```
  - name: tests error from rule engine request deletes root
    target_processors: 'rule_engine_request'
    mocks:
      make_rule_engine_http_request:
        mapping: throw("some error")
    metadata:
      - "http_status_code": "500"
    input_batch:
      - json_content:
          "test1": "test1"
    output_batches: []
```

When I run the test, I get:
`unexpected batch: [{"test1":"test1"}]`

Can someone help me what am I missing or if my understanding of `root` is completely wrong?
Slighty related: is this even the right way to mock failed http processor with a `500` response?

**Comment by mihaitodor** [comment]
Hey @mariamjamal94 👋 If you run the tests with `--log=debug` you'll see some hints. It should show you a message saying that "Child processors failed: child processors resulted in zero messages", which basically means that the number of messages going inside a `branch` processor needs to be equal to the number of messages coming out of it. Because of this, you can't just delete a message in there. What you can do, for example, is to set `meta error = error()` and then, in the `result_map`, you can have `root = if metadata("error") != null { throw(metadata("error")) } else { this }`. Something like this:

```yaml
input:
  generate:
    count: 1
    mapping: root = ""
  processors:
    - branch:
        processors:
          - mapping: throw("Kaboom!")

          - catch:
              - mapping: meta error = error()

        result_map: |
          root = if metadata("error") != null { throw(metadata("error")) } else { this }
    - catch:
        - mapping: root = deleted()

tests:
  - name: tests branch processor
    target_processors: "/input/processors"
    input_batch:
      - json_content:
          foo: "bar"
```

Also, not sure why you have `tests[].metadata` in there, but you should use [`tests[].input_batches[][].metadata`](https://www.benthos.dev/docs/configuration/unit_testing#testsinput_batchesmetadata) instead. I was kinda' expecting to get an error since you're using an undocumented field, but maybe it's some leftover.
