### DISCUSSION TITLE
http_server sync response brokered with an other output and batching

### DISCUSSION THREAD

**Discussion by sagikazarmark** [redpanda-data/connect#2324] [General]
I have the following pipeline:

```yaml
input:
  http_server:
    address: 0.0.0.0:4196
    path: /api/v1/events
    sync_response:
      status: '${! meta("http_response_status").or("204") }'

output:
  broker:
    pattern: fan_out
    outputs:
      - sync_response: {}
        processors:
          - mapping: root = null
      - http_client:
          # ...
          batching:
            count: 20

```

The problem I have is reaching the desired count may take a long time and HTTP requests time out.

The reason I use sync response in the first place is being able to modify the response code (also, I have a couple processors validating the messages and I return an error in the response if the request is invalid).

Ideally, I'd like to return the response without waiting for the http_client request to be sent.

Is that possible?

Thanks!
