### DISCUSSION TITLE
cache types: how do I identify error types?

### DISCUSSION THREAD

**Discussion by smousa** [redpanda-data/connect#2442] [Q&A] [answered]
Hello,

When building a readthrough cache in a pipeline, is there a way I can distinguish from an error where I get a cache miss vs some other type of error?

```yaml
processor_resources:
  - label: get
    processors:
      - try:
        - cache:
            resource: my_cache
            operator: get
            key: MYKEY
      - catch: # how do identify what I am catching is no records found or something is wrong with the cache?
        - branch:
            result_map: root.value = this
            processors:
              - resource: call_database
        - branch:
            result_map: root = this.value
            processors:
              - try:
                - cache:
                    resource: my_cache
                    operator: add
                    key: MY_KEY
                    value: this.value
```
