### DISCUSSION TITLE
Mqtt password in environment variable

### DISCUSSION THREAD

**Discussion by alessandro-gomma** [redpanda-data/connect#2451] [Q&A] [answered]
Hi!

We are facing a problem while trying to move the password that we use to connect to mqtt to an environment variable.

We feel that the problem _might_ be caused by the presence of the **$** character in the password (the password we are using is **Benthos1234!$@**)

The other parameters (url, user, ecc) are correctly retrieved, so we exclude an issue on that side; we also tried to escape the password parameter (${{MQTT_PASSWORD}}) as suggested in the Interpolation guide

Here's part of the configuration file we are using:

```
input:
  mqtt:
    urls: ["${MQTT_URL}"]
    client_id: 
    user: "${MQTT_USER}"
    password: "${MQTT_PASSWORD}"
    connect_timeout: 30s
    qos: 1
    topics: ["command/${TENANT_ID}/#"]
```
