### DISCUSSION TITLE
Cross region buckets using the aws_s3 input

### DISCUSSION THREAD

**Discussion by ryanpodonnell1** [redpanda-data/connect#2452] [General]
I have an input like this, which works fine. The problem I am having is that it appears not to be able to pull from buckets in different regions. Is there some dynamic way I can pull the region of the bucket in?

```yaml
input:
  label: "${Workspace:dev}_conscan"
  aws_s3:
    bucket: "${BENTHOS_ConscanS3Bucket}"
    scanner:
      lines: {}
    codec: gzip/all-bytes
    sqs:
      url: "${BENTHOS_ConscanSqsQueue}"
      key_path: detail.object.key
      bucket_path: detail.bucket.name
      max_messages: 10
      wait_time_seconds: 0
```

so it can end up like this?

```yaml
input:
  label: "${Workspace:dev}_conscan"
  aws_s3:
    bucket: "${BENTHOS_ConscanS3Bucket}"
    region: detail.bucket.region <= here so I can force the regional endpoint?
    scanner:
      lines: {}
    codec: gzip/all-bytes
    sqs:
      url: "${BENTHOS_ConscanSqsQueue}"
      key_path: detail.object.key
      bucket_path: detail.bucket.name
      max_messages: 10
      wait_time_seconds: 0
```
