### DISCUSSION TITLE
How to make "negative" unit tests?

### DISCUSSION THREAD

**Discussion by alessandro-gomma** [redpanda-data/connect#2490] [Q&A] [answered]
In our streams we would like to create some unit tests to verify that when the stream process a broken message, the stream handles the error correctly (logging, eventual post-processing, etc..).

If we write a unit test with a broken message as input, the stream correctly handles the error but the test fails with the _"wrong batch count, expected 1, got 0"_ message.

Is there any way to test this?

Sample configuration as reference:
```
input:
  broker:
    inputs:
      <<< input >>>
pipeline:
  processors:
    - mapping: |
      <<< map & process>>>
    - catch:
        - log:
            level: ERROR
            message: "Processing failed due to: ${!error()} | message ${!content()}"
        - mapping: root = if errored() { deleted() }
output:
  <<< output >>>

```

Thanks!

**Comment by mihaitodor** [comment, marked as answer]
Hey @alessandro-gomma 👋 One approach is to write a test which expects 0 batches:

```yaml
pipeline:
  processors:
    - mapping: |
        root = throw("kaboom!")
    - catch:
        - mapping: root = if errored() { deleted() }

tests:
  - name: test deleted
    target_processors: '/pipeline/processors'
    input_batch:
      - content: 'foobar'
    output_batches: []
```

Alternatively, depending on what your pipeline does and where you place that `mapping` processor which contains the `deleted()` call, you could [mock](https://www.benthos.dev/docs/configuration/unit_testing#mocking-processors) it such that it returns some dummy data instead. Something like this:

```yaml
pipeline:
  processors:
    - mapping: |
        root = throw("kaboom!")
    - catch:
        - label: mockme
          mapping: root = if errored() { deleted() }


tests:
  - name: test deleted
    target_processors: '/pipeline/processors'
    mocks:
      mockme:
        mapping: root = "ERROR"
    input_batch:
      - content: 'foobar'
    output_batches:
      -
        - content_equals: ERROR
```
