### DISCUSSION TITLE
Templating "processor"

### DISCUSSION THREAD

**Discussion by doffi88** [redpanda-data/connect#2505] [Q&A]
Hi all,

I'm trying to template a processor but I don't understand how to create the template file.

my template is the following:

```yaml
name: twins
type: processor

fields:
  - name: ids
    type: string
    kind: list
    default:
      - input/test
  - name: outputs
    type: string
    kind: list
    default:
      - prova

mapping: |
  root.switch = []
  root.switch."-".check = "@mqtt_topic == this.ids.index(0)"
  root.switch."0".processors = []
  root.switch."0".processors."-".mapping = "meta output_topic = this.outputs.index(0)"
  root.switch."0".processors."-".resource = "sample"
  root.switch."-".processors = []
  root.switch."1".processors."-".mapping = "root = deleted()"
```

my config file is the following:

```yaml
input:
  mqtt:
    urls:
      - mqtt://mosquitto:1883
    topics:
      - input/+

processor_resources:
  - label: sample
    mapping: |
      root.specversion = "1.0"
      root.type = @mqtt_topic
      root.datacontenttype = this.headers."content-type"
      root.source = "benthos"
      root.id = this.headers."correlation-id"
      root.causationid = this.headers."correlation-id"
      root.correlationid = this.headers."correlation-id"
      root.time = now()
      root.data = this.value

pipeline:
  processors:
    - twins:
        ids:
          - input/test
        outputs:
          - prova

output:
  nats:
    urls:
      - nats://nats:4222
    subject: ${! @output_topic }
```

the expected result is:

```yaml
input:
  mqtt:
    urls:
      - mqtt://mosquitto:1883
    topics:
      - input/+

processor_resources:
  - label: sample
    mapping: |
      root.specversion = "1.0"
      root.type = @mqtt_topic
      root.datacontenttype = this.headers."content-type"
      root.source = "benthos"
      root.id = this.headers."correlation-id"
      root.causationid = this.headers."correlation-id"
      root.correlationid = this.headers."correlation-id"
      root.time = now()
      root.data = this.value

pipeline:
  processors:
    - switch:
        - check: '@mqtt_topic == "input/test"'
          processors:
            - mapping: |
                #let result = this.topic.split("/")
                #meta output_topic = $result.index(1)
                meta output_topic = "prova"
            - resource: sample
        - processors:
            - mapping: root = deleted()

output:
  nats:
    urls:
      - nats://nats:4222
    subject: ${! @output_topic }
```

How can i write the template in order to obtain this result?

Thank you very much
