### DISCUSSION TITLE
`http` processors send body on `GET`

### DISCUSSION THREAD

**Discussion by mskarbek** [redpanda-data/connect#2533] [Q&A]
For:
```
pipeline:
  threads: -1
  processors:
    - branch:
        processors:
          - http:
              url: "https://REDACTED/service/rest/v1/components?repository=${! this.repo}"
              verb: GET
              headers:
                Accept: "application/json"
        result_map: "root.response = this"
```
I received 415 error from Sonatype Nexus server. Adding `TRACE` level of logging revealed that Benthos adds body to the request even if it is a `GET` which in turn upsets Nexus.
Is there a way to avoid sending body with `GET` requests?

**Comment by packman80** [comment]
From documentation:

> A [Bloblang mapping](https://www.benthos.dev/docs/guides/bloblang/about) that describes how to create a request payload suitable for the child processors of this branch. If left empty then the branch will begin with an exact copy of the origin message (including metadata).

You need to get empty message without copy of original message. In this case you avoid sending body in GET request. Use it:

```
pipeline:
  threads: -1
  processors:
    - branch:
        request_map: root = "" 
        processors:
          - http:
              url: "https://REDACTED/service/rest/v1/components?repository=${! this.repo}"
              verb: GET
              headers:
                Accept: "application/json"
        result_map: "root.response = this"
```
