### DISCUSSION TITLE
Unable to use Protobuf primitive wrapper types

### DISCUSSION THREAD

**Discussion by Zambito1** [redpanda-data/connect#2543] [Q&A] [answered]
I am trying to deserialize Protobuf messages that use the Any type, and uses some of the wrapper types for compatibility with primitive types. Particularly those found [here](https://protobuf.dev/reference/protobuf/google.protobuf/). Here is a minimal example that demonstrates the issue I am running into. The following works:

`person.proto`:
```protobuf
syntax = "proto3";

import "google/protobuf/any.proto";

message PersonWorks {
  string name = 1;
  bool is_tall = 2;
}

message PersonBroken {
  google.protobuf.Any name = 1;
  google.protobuf.Any is_tall = 2;
}
```
`config.yaml`:
```yaml
input:
  generate:
    mapping: |
      root.name = fake("name")
      root.isTall = random_int(max:1) == 1
    interval: 1s
    count: 10

pipeline:
  processors:
    - protobuf:
        operator: from_json
        message: "PersonWorks"
        import_paths: [.]
    - protobuf:
        operator: to_json
        message: "PersonWorks"
        import_paths: [.]
```
(worth noting that the round trip maps `false` to `null`, but that is not the issue I am trying to cover here)

But this does not:
`config.yaml`:
```yaml
input:
  generate:
    mapping: |
      root.name = fake("name")
      root.isTall = random_int(max:1) == 1
    interval: 1s
    count: 10

pipeline:
  processors:
    - mapping: |
        root.name = {
          "@type": "type.googleapis.com/google.protobuf.StringValue",
          "value": this.name
        }
        
        root.isTall = {
          "@type": "type.googleapis.com/google.protobuf.BoolValue",
          "value": this.isTall
        }
    - protobuf:
        operator: from_json
        message: "PersonBroken"
        import_paths: [.]
    - catch:
        - log:
            level: ERROR
            message: "Error: ${!error()}"
        - mapping: |
            root = deleted()
    # - protobuf:
        # operator: to_json
        # message: "PersonBroken"
        # import_paths: [.]
```

It fails with the following log:
```
ERRO Error: failed to unmarshal JSON message 'PersonBroken': proto: (line 1:20): unable to resolve "type.googleapis.com/google.protobuf.BoolValue": "not found"  @service=benthos label="" path=root.pipeline.processors.2.catch.0
```

If I remove the `BoolValue` field, I get the same error with the `StringValue` field instead. It seems to be related to this issue: https://github.com/golang/protobuf/issues/1156 but I tried adding
```go
import (
     // ...
    _ "google.golang.org/protobuf/types/wrapperspb"
)
```
xor

```go
import (
     // ...
    _ "github.com/golang/protobuf/ptypes/wrappers"
)
```

to `internal/impl/protobuf/processor_protobuf.go`, and neither worked.

**Comment by Zambito1** [comment]
Surprisingly though this actually works:

`person.proto`:
```protobuf
syntax = "proto3";

import "google/protobuf/wrappers.proto";

message PersonWorks {
  string name = 1;
  bool is_tall = 2;
}

message PersonBroken {
  google.protobuf.StringValue name = 1;
  google.protobuf.BoolValue is_tall = 2;
}
```

`config.yaml`:
```yaml
input:
  generate:
    mapping: |
      root.name = fake("name")
      root.isTall = random_int(max:1) == 1
    interval: 1s
    count: 10

pipeline:
  processors:
    - protobuf:
        operator: from_json
        message: "PersonBroken"
        import_paths: [.]
    - catch:
        - log:
            level: ERROR
            message: "Error: ${!error()}"
        - mapping: |
            root = deleted()
    - protobuf:
        operator: to_json
        message: "PersonBroken"
        import_paths: [.]
```

This is with the latest on `main` rather than with my added imports too. The issue is specifically related to using these types with `google.protobuf.Any`
