### DISCUSSION TITLE
Is it possible to stream responses from the HTTP processor?

### DISCUSSION THREAD

**Discussion by Zambito1** [redpanda-data/connect#2546] [General]
The `http_client` has a [stream](https://www.benthos.dev/docs/components/inputs/http_client#stream) field that allows you to break the response into a series of messages. I am trying to use Benthos to link sources to Ollama, which has a streaming API. I tried using the `unarchive` processor, but that will still block until the reply is complete, which is not ideal. Here is what I currently have:

```yaml
pipeline:
  processors:
    - mapping: |
        root.model = ${LANGUAGE_MODEL}
        root.messages = [
          {
            "role": "user",
            "content": content().string()
          }
        ]
        root.stream = true
    - http:
        url: "http://${OLLAMA_HOST}/api/chat"
        timeout: 15s
    - unarchive:
        format: json_documents
```

The timeout must be set higher than the total response time from the API as well, which (though I have not tested) I assume is not required with the `http_client` `timeout` field. Is it possible to do what I want with the `http` processor?
