### DISCUSSION TITLE
Have a `file` input to periodically check for files

### DISCUSSION THREAD

**Discussion by antipopp** [redpanda-data/connect#2559] [Q&A] [answered]
I'm trying to build a configuration that among other things should periodically check the specified path for a file, but I'm lost on how to implement this.

I've tried to mix it up with a `generate` and `sequence` input, hoping the former would trigger the `file` one but it doesn't work.
```yaml
input:
  sequence:
    inputs:
      - generate:
          mapping: |
            root = {
              "auto": true
            }
          interval: 10s
      - file:
          paths: ["./*.json"]
          scanner:
            lines: {}
          delete_on_finish: false

ouput:
   stdout: {}
```

Using a `broker` also has the same faith, the file input is run only once while the generate keeps going with its behavior.
Has anybody found any workaround on this other than cronifying the execution of the config?

**Comment by mihaitodor** [comment, marked as answer]
Hey @antipopp 👋 You can wrap the input in a `read_until` input with `check: false` and `restart_input: true`. If you need to sleep a bit between runs, you can keep the `sequence` and wrap that in the `read_until` input, but you’ll have to set `count: 1` under `generate` and attach a `sleep` processor followed by a `mapping: root = deleted()` to get rid of the message that `generate` creates. See a similar example here: https://github.com/redpanda-data/connect/issues/2005#issuecomment-1644883146

**Reply by antipopp** [reply]
Thanks!

**Comment by pritster5** [comment]
Just wanted to post a slightly more fleshed out version of this idea here:

```
---
input:
  read_until:
    check: false
    restart_input: true
    input:
      sequence:
        inputs:
          - generate:
              mapping: root = ""
              interval: 1s
              count: 1
            processors:
              - sleep:
                  duration: 30s
              - mapping: root = deleted()
          - file:
              paths: ["./fileWatcherTests/*.txt"]
              scanner:
                to_the_end: {}
              delete_on_finish: true
output:
  file:
    path: ./fileWatcherTests/rpk_output/${! timestamp_unix() }.txt
```

This will periodically check a directory for txt files and write the entire contents of each file to a corresponding file in another directory. The process will be kept perpetually running via rpk connect run connect.yaml
