### DISCUSSION TITLE
Error when running redpanda connect in multiple pods with NATS Jetstream as input.

### DISCUSSION THREAD

**Discussion by BenBasilTomy** [redpanda-data/connect#2695] [Q&A] [answered]
I am running a redpanda  connect with NATS Jetstream as input and getting an error: 
"**Failed to connect to nats_jetstream: cannot create a queue subscription for a consumer without a deliver group.**"
But as per redpanda connect documentation there is no config field for NATS Jetstream input as deliver group. How to solve this? Below is my input configuration:
```
input:
  label: orders_publisher
  nats_jetstream:
    urls: [nats://nats:4222]
    subject: awsloadtest
    stream: orders
    queue: testqueue
    durable: awsloadtest 
    ack_wait: 30s
    max_ack_pending: 1000
    deliver: all
```
