### DISCUSSION TITLE
Slow throughput with aws_s3 output

### DISCUSSION THREAD

**Discussion by dbason** [redpanda-data/connect#2790] [Q&A] [answered]
We have some flows where we read from a kafka input, run through an avro processor and then write to an s3 bucket.  We seem to be hitting a flat max throughput which we're reasonably sure isn't the s3 request rate limit.

Our pipeline is as follows:
```
input:
      label: "kafka"
      kafka:
        addresses: [ "${KAFKA_BROKERS}" ]
        topics: 
          - datastream
        consumer_group: consumer_group_name
        client_id: outrider_kafka_input
        start_from_oldest: false
        group:
          session_timeout: 10s
          heartbeat_interval: 3s
          rebalance_timeout: 60s
        fetch_buffer_cap: 256
        target_version: 1.0.0
        batching:
          count: 10000
          period: 60s

    pipeline:
      processors:
        - avro:
            operator: to_json
            encoding: binary
            schema_path: "file:///config/avro.schema"

    output:
      switch:
        cases:
          - check: some condition
            continue: true
            output:
              aws_s3:
                max_in_flight: 300
                bucket: "bucketname"
                region: "us-east-2"
                credentials:
                  id: "${AWS_ACCESS_KEY}"
                  secret: "${AWS_ACCESS_KEY_SECRET}"
                path: out/output/path
                batching:
                  count: 10000
                  period: 60s
                  processors:
                    - archive:
                        format: lines

          - output:
              drop: {}
```

With this config we end up hitting an absolute maximum of 222 messages per second.  If we double the input batching to 20000 we get a max of 444 which makes me think the limiting factor is the output.  If the condition isn't met and it goes to the drop output it processes extremely quickly.  We have also tried tuning the `max_in_flight` setting with not appreciable changes in throughput.

We are running the latest docker image that was published under `jeffail/benthos`

Is there anything obviously wrong?
