### DISCUSSION TITLE
[input_mongodb] Bloblang query is not working with ISODate field

### DISCUSSION THREAD

**Discussion by lytuan99** [redpanda-data/connect#2890] [Q&A] [answered]
#### I've tried many ways in configuring input below, all of those command can not get data.

```yml
    query: |
      root.createdAt = {"$lte": now()}
## in history queries mongodb: "$lte": "2024-09-22T08:58:00.139917+07:00"
##
    query: |
      root.createdAt = {"$lte": timestamp_unix() - 90 * 86400}
## in history queries mongodb: "$lte": new NumberInt("1597405526")
##
    query: |
      root.createdAt = {"$gte": (timestamp_unix() - 90 * 86400).ts_format()}
## in history queries mongodb: "$gte": "2024-06-24T08:58:55+07:00"
## .....
```

#### In my IDE, I execute the query below, and it works.
```js
db.orders.find({
  createdAt: {
    $gte: new Date("2024-02-02"),
  },
});
```
![image](https://github.com/user-attachments/assets/8688caa1-9914-4ddb-b87a-863931a53f17)

Did I miss something or the RedPanda-connect should add a new feature for ISODate object?

**Comment by mihaitodor** [comment, marked as answer]
Hey @lytuan99 👋 Try `root.created_at = {"$gte": "2024-02-02".ts_strptime("%Y-%m-%d")}` for example. Also, this should work: `root.created_at = {"$gte": now().ts_parse("2006-01-02T15:04:05Z07:00")}`. The `2006-01-02T15:04:05Z07:00` format is the reference format used for RFC3339 in Go as documented here: https://pkg.go.dev/time#pkg-constants.

PS: Converting this to a discussion as mentioned in #2026.

**Comment by lytuan99** [comment]
@mihaitodor Thanks for your response. it worked.
btw, here is the way I want to do:
```yml
    json_marshal_mode: canonical
    query: |
      root.createdAt = {"$gte": (timestamp_unix() -  86400).ts_format("2006-01-02").ts_strptime("%Y-%m-%d")}
```
