### DISCUSSION TITLE
Is it any possibility to define and use variables in tests

### DISCUSSION THREAD

**Discussion by YuriiYa** [redpanda-data/connect#2968] [General]
Define variables inside `environment` and use inside `mocks, input_batch, output_batches`.
It will greatly help in case you have complex testcase and need to focus reader on some specific aspect for ex what was changed. 

Something like that:
```yaml
 - name: When_And_Then
    target_processors: "../jobs/benthos.yaml#/pipeline/processors"
    environment: 
     var1: "1"
     var2: "2"
     var3: "3"
     var4: "3"
    mocks:
      get_cached_data:
        mapping:  | 
            meta cached = { "pickup": $var1  }
    input_batch:
      - content: |-
          {
            "Code": $var2
          }
        metadata:
          orderId: "${! $var3}"
    output_batches:
      -
        - json_equals: |-
            {
                "data": $var4
            }
```
 Didn't find anything in documentation
