### DISCUSSION TITLE
How to set special characters in `custom_delimiter`

### DISCUSSION THREAD

**Discussion by dacalabrese** [redpanda-data/connect#3000] [Q&A]
Hi all,

I'm trying to configure a `socket` input to receive data stream sent via a TCP server. Messages are unstructured binary data, but I can configure the sender to insert a defined sequence between frames (i.e. messages).

This is to prevent messages from being buffered indefinitely. The sequence `1acffc1d` is the hexadecimal representation of the binary data.

I've tried the following configuration, with no luck:
```
input:
  label: socket
  socket:
    network: "tcp"
    address: "127.0.0.1:60002"
    auto_replay_nacks: true
    scanner:
      lines:
        custom_delimiter: "\x1a\xcf\xfc\x1d"
```

Is there a way to specify a delimiter of such type (i.e. byte sequence)? For instance, I tried `"\x1a\xcf\xfc\x1d"` or `"\\x1a\\xcf\\xfc\\x1d"` but they are not interpreted as bytes.

Thank you!

**Comment by mihaitodor** [comment]
Hey @dacalabrese, sorry for the late reply! Please try this:

```yaml
input:
  label: socket
  socket:
    network: "tcp"
    address: "127.0.0.1:60002"
    auto_replay_nacks: true
    scanner:
      lines:
        custom_delimiter: !!binary Gs/8HQ==
```

Note: The `!!binary` tag requires the bytes to be base64-encoded. See the docs [here](https://yaml.org/type/binary.html).
