### DISCUSSION TITLE
lint error when define `rate_limit_resources` and use it

### DISCUSSION THREAD

**Discussion by fearfate** [redpanda-data/connect#3072] [Q&A] [answered]
```yaml
# data_pipeline/business/ydevops.yml
rate_limit_resources:
  - label: ydevops_limit
    local:
      count: 20
      interval: 1s

input:
  label: ydevops_input
  git:
    repository: https://github.com/xxxxxx/ydevops.git
    branch: main
    cache_dir: /opt/ysdb_worker/data/cache/ydevops
    pattern: >-
      **.cdx.json
  processors:
    - rate_limit:
        resource: ydevops_limit
```

got a lint error:

![image](https://github.com/user-attachments/assets/5e2df803-eac6-4393-bcb5-f04182f56331)
