### DISCUSSION TITLE
how to convert message to batch message for `parquet_encode` in output

### DISCUSSION THREAD

**Discussion by fearfate** [redpanda-data/connect#3074] [Q&A] [answered]
example config like this:

```
pipeline:
  processors:
  - mapping: |
      root = [{"key1": "value1"}, {"key1": "value2"}, {"key": "value2"}] 
  - unarchive:
      format: json_array
output:
  switch:
    cases:
    - check: |
        this.exists("key1")
      output:
        broker:
          copies: 1
          pattern: fan_out
          outputs:
          - file:
              path: example-${! timestamp_unix_nano() }.parquet
              codec: all-bytes
         batching:
            byte_size: 104857600
            period: 3m
            processors:
            - parquet_encode:
                schema:
                - name: key1
                  type: UTF8
    - check: |
         this.exists("key")
       output:
         drop: {}
```

but I will got two parquet file, and I tried `group_by_value` and `archive: format: json_array`, not work as i was expected. Is there any way to convert message to batch message in output?
