### DISCUSSION TITLE
How to send kafka tombstones?

### DISCUSSION THREAD

**Discussion by radovsky1** [redpanda-data/connect#3181] [Q&A]
Hi! I have the following pipeline, the result, where mapper(javascript) creates an array of json objects, each of which has a {key}:{message to kafka}, faced with the question of how to send Kafka tombstones? tried {key}:{null}, {key}:{""}, everything is interpreted as a string, how to implement a message as zero bytes?

```
  processors:
    - try:
        - javascript:
            file: ${MAPPER_FILE:/config/mapper.js}
        - mapping: root = this.instruments
        - unarchive:
            format: json_array
        - unarchive:
            format: json_map
    - catch:
        - log:
            level: ERROR
            message: "processor failed: ${!error()}"
            fields_mapping: |
              root.value = this
        - mapping: root = deleted()
output:
  kafka:
```
