### DISCUSSION TITLE
Unable to infer component type: processors, msg: Config lint error

### DISCUSSION THREAD

**Discussion by a-a-ron-manzano** [redpanda-data/connect#3248] [Q&A] [answered]
Recently upgraded from a v4.27.0 Benthos container to a Redpanda Connect v4.49.1 container. Some unchanged yaml configs with the same pattern have started failing with a linting error:

![Screenshot from 2025-03-07 14-03-50](https://github.com/user-attachments/assets/193de522-6770-42b3-95b7-57d80cd70ef2)

It seems to be complaining about the processors at ln #'s 63 & 78 under the output broker. Not sure how I'm supposed to "specify an explicit output type" ??

![Screenshot from 2025-03-07 14-05-41](https://github.com/user-attachments/assets/78304a98-e661-4d93-bb2d-2fb0ecbc4219)

Any help would be greatly appreciated!!!

Thank you!!
~Aaron

**Comment by mihaitodor** [comment, marked as answer]
Hey @a-a-ron-manzano, I'd need to see a bit more of your config, but I think that's because you have something like this:

```yaml
output:
  broker:
    pattern: fan_out
    outputs:
      - processors:
          ...
      - processors:
          ...
```

What you really should have is this:

```yaml
output:
  broker:
    pattern: fan_out
    outputs:
      - first_output:
          ...
        processors:
          ...
      - second_output:
          ...
        processors:
          ...
```

I guess in your case both `first_output` and `second_output` were `stdout` implicitly, but the linter got a bit more strict since then. If that's the case, then you can do this:

```yaml
output:
  broker:
    pattern: fan_out
    outputs:
      - stdout: {}
        processors:
          ...
      - stdout: {}
        processors:
          ...
```
