### DISCUSSION TITLE
how to use cache memory?

### DISCUSSION THREAD

**Discussion by tri0mphe** [redpanda-data/connect#3318] [Q&A]
```yaml
pipeline:
  threads: 2
  processors: 
    - mapping: |
        meta src_ip = this.src_ip
        meta username = ""
    - branch:
        request_map: |
          root = ""
        processors:
          - cache:
              operator: get
              resource: ip_username_cache  # 缓存资源名称
              key: "${! meta(\"src_ip\")}"  # 使用消息中的 src_ip 作为缓存键
          - catch:
            - log:
                level: ERROR
                message: "缓存查询失败: ${! error() }"
            - mapping: |
                root = ""
        result_map: |
          meta username = if this != null { this } else { "" } 
    - branch:
        request_map: |
          root = if @username == "" {
            ""
          } else {
            deleted()  # 跳过此分支
          }
        processors:
          - http:
              url: "http://test.com/api/v1/ipUserQuery?ip=${! meta(\"src_ip\") }&needIpType=true&needHistory=true&needUserInfo=true" # No default (required)
              verb: GET
              timeout: 5s
              headers:
                Accept: "application/json"
        result_map: |
          meta username = this.username
          root.username = this.username
          root.bg = this.bg
          root.department = this.departmentName
          root.department_chain = this.orgChainNameCn
    - cache:
        operator: set
        resource: ip_username_cache  # 缓存资源名称
        key: "${! meta(\"src_ip\")}"  # 使用消息中的 src_ip 作为缓存键
        value: "${! meta(\"username\") }"
    - branch:
        request_map: |
          root = ""
        processors:
          - cache:
              operator: get
              resource: ip_username_cache  # 缓存资源名称
              key: "${! meta(\"src_ip\")}"  # 使用消息中的 src_ip 作为缓存键
        result_map: 'root.username_get = this'

output:
  stdout: {}

cache_resources:
  - label: ip_username_cache
    memory:
      default_ttl: 2m
      compaction_interval: 60s
      init_values: {}
```

The cache is not running properly. I don't know why
