### DISCUSSION TITLE
URL-encoded HTTP requests

### DISCUSSION THREAD

**Discussion by mihaitodor** [redpanda-data/connect#3419] [Show and tell]
Here's a sample config which shows how to perform a `application/x-www-form-urlencoded` HTTP POST request:

```yaml
input:
  generate:
    count: 1
    mapping: |
      root.foo = "bar"
      root.fizz = "buzz"
  processors:
    - mapping: |
        root = this.key_values().map_each(kv -> kv.key + "=" + kv.value).join("&")
    - http:
        url: http://localhost:6666
        verb: "POST"
        headers:
          Content-Type: "application/x-www-form-urlencoded"
```
