### DISCUSSION TITLE
How to output a message after all the input messages were processed

### DISCUSSION THREAD

**Discussion by mihaitodor** [redpanda-data/connect#3431] [Show and tell]
You can use the `sequence` input to have a `generate` input fire off a message for the last event. In the example below, the first `generate` input is just a placeholder for a finite input. If your input is already `generate`, you might be tempted to increment `count` by one to get an extra message so you don't need the `sequence` input, but that's unreliable because the `generate` input can emit multiple messages in parallel, so your final message could land in the output before all the others have been written.

```yaml
input:
  sequence:
    inputs:
      - generate:
          count: 2
          mapping: root = "foo"
      - generate:
           count: 1
           mapping: root = "end"
  processors:
    - switch:
        - check: content() == "foo"
          processors:
            - sleep:
                duration: 1s

output:
  switch:
    cases:
      - check: content() == "foo"
        output:
          stdout: {}
        processors:
          - log:
              message: "First output"
      - output:
          stdout: {}
        processors:
          - log:
              message: "Second output"
```
