### DISCUSSION TITLE
Elasticsearch 9.0.1: media_type_header_exception

### DISCUSSION THREAD

**Discussion by terebentina** [redpanda-data/connect#3436] [Q&A]
Hi folks,

I'm trying my first pipeline with redpanda connect with a very simple scenario: pick from kafka, save to elasticsearch.
However, I get an error message I have no idea how to solve: `Failed to send message to elasticsearch_v8: sending bulk request: status: 400, failed: [media_type_header_exception], reason: Invalid media-type value on headers [Accept, Content-Type]`.

My elasticsearch server is `9.0.1` and I am using the `elasticsearch_v8` output connector. I'm thinking it's because of the version mismatch but not sure since I can't see the actual headers.
Have you tested this against 9.x servers or is there any plan on releasing an `elasticsearch_v9` connector?

My output config is really simple:
```
output:
  label: ""
  elasticsearch_v8:
    urls:
      - ${ES_URL}
    index: stream-v1-${! meta("org") }
    action: "create"
    id: ${!counter()}-${!timestamp_unix()}
    max_in_flight: 100
    tls:
      enabled: true
      skip_cert_verify: true
```
