### DISCUSSION TITLE
amqp_0_9 authentication with certificates only?

### DISCUSSION THREAD

**Discussion by zswanson** [redpanda-data/connect#761] [Q&A] [answered]
Hello! I'm trying see if I can get benthos working with amqp_0_9 input against a TLS secured rabbitmq cluster that uses 'passwordless users' with x509 certs for authentication.  

https://www.rabbitmq.com/passwords.html#x509-certificate-authentication
>It is possible to authenticate connections using x509 certificates and avoid using passwords entirely. The authentication process then will rely on TLS peer certificate chain validation.
> To do so:
> Create a passwordless user (see above)
> Enable the rabbitmq-auth-mechanism-ssl plugin
> Follow the plugin's configuration instructions
> Configure client connections to use TLS and the EXTERNAL authentication mechanism
> Configure client connections to provide a certificate/key pair and a CA certificate (or chain of certificates). The chain of certificates will be verified by the server and thus at least one certificate in it must be trusted by the target node.

Is there a way to configure this correctly for amqp 0.9? I keep getting errors from benthos and my rabbit cluster that its trying to connect as a guest user, despite that I've left the user/password empty in the url and have provided the TLS cert configuration.

According to the rabbitmq docs 

```
input:
  amqp_0_9:
    url: amqps://my.rabbitmq.cluster:5671/%2f
    queue: benthos
    tls:
      enabled: true
      enable_renegotiation: true
      skip_cert_verify: false
      root_cas_file: ./ca-bundle.pem
      client_certs:
        - key_file: ./key.pem
          cert_file: ./cert.pem
```
