### ISSUE TITLE
Invalid output file name succeeds ambiguously

### ISSUE THREAD

**Issue by Tapuzi** [redpanda-data/connect#1005]
Unsupported characters in output file path result in a non defined behavior.
For example:
```
input:
  type: stdin

output:
  file:
    path: 'sample_${! now().format_timestamp_strftime("%Y-%e-%dT%H:%M") }.json'
```

File is saved but the path is trimmed, similar to `sample_2021-10-10T23`
