### ISSUE TITLE
Infinite retry loop in `gcp_pubsub` output when used with `kafka` input and non-string message keys

### ISSUE THREAD

**Issue by torfjor** [redpanda-data/connect#1042]
Upstream issue: https://github.com/googleapis/google-cloud-go/issues/5268
Related: https://github.com/googleapis/google-cloud-go/issues/2443

This basically breaks the `gcp_pubsub` output for anyone consuming from a `kafka` input where the message keys are not strings.

Attaching a processor that removes the `kafka_key` metadata solves the issue temporarily until we have a fix:
```yaml
pipeline:
  processors:
    - bloblang: |
        meta kafka_key = deleted()
````
