### ISSUE TITLE
ElasticSearch output: Ignore message content

### ISSUE THREAD

**Issue by szalai1** [redpanda-data/connect#1168]
ElasticSearch output fails with `Failed to dispatch switch message: failed to marshal message into JSON document: target message part does not exist` 
if the action is `delete` and the content is empty. 

In case of deletion, content doesn't need to be parsed.

**Comment by szalai1** [comment]
The workaround suggested by @Jeffail 


Note the processor:
```
output:
  switch:
    cases:
    - check: content().length() == 0
      output:
        elasticsearch:
          urls:
            - '${OPENSEARCH_URL}'
          index: answer_keyphrases
          id: ${! meta("kafka_key") }
          type: _doc
          max_in_flight: 1
          action: "delete"
          sniff: false
        processors:
          - bloblang: 'root = {}'
  ```
