### ISSUE TITLE
Feature Request: Support network errors in http retries

### ISSUE THREAD

**Issue by julez-dev** [redpanda-data/connect#1285]
Hey!

It seems like the http_clients built-in retry fails directly if the target host is not reachable.

Consider this configuration file:

```yaml
input:
  http_server:
    address: ":8080"
    path: /post
    allowed_verbs:
      - POST

pipeline:
  processors:
    - noop: {}

output:
  http_client:
    url: "http://not-reachable"
    verb: GET
    retries: 4
```

This will result in the following log message:

```
ERRO Failed to send message to http_client: http://not-reachable: Get "http://not-reachable": dial tcp: lookup not-reachable on 192.168.178.1:53: no such host  @service=benthos label="" path=root.output
```

One workaround for this problem is wrapping the http_client inside a retry output like this:

```yaml
output:
  retry:
    max_retries: 4
    output:
      http_client:
        url: "http://not-reachable"
        verb: GET
        retries: 4
```

This comes with the drawback that the retry is sometimes triggered, even when it's not necessary for example on 400 responses.

```yaml
output:
  retry:
    max_retries: 4 # will retry
    output:
      http_client:
        url: "http://returns-400"
        verb: GET
        retries: 4 # won't retry
        drop_on: [400]
``` 

Is there a better workaround for this problem or is there a possibility that in the future network errors will trigger the http_client retry if for example a new setting is set?

Thank you
