### ISSUE TITLE
Add support for parquet logical types to parquet_encode processor

### ISSUE THREAD

**Issue by mihaitodor** [redpanda-data/connect#1392]
In some cases, users will need to specify the logical type in the `schema` field. Details here: https://github.com/apache/parquet-format/blob/master/LogicalTypes.md

For example, when using `type: BYTE_ARRAY` to encode a string value, they might want to set the logical type to `STRING` so decoders will be able to interpret it correctly. For example, given this config:

```yaml
input:
  generate:
    mapping: root.test = "deadbeef"
    count: 1
    interval: 0s

pipeline:
  processors:
    - parquet_encode:
        schema:
          - name: test
            type: BYTE_ARRAY

output:
  file:
    path: output.parquet
    codec: all-bytes
```

will produce a parquet binary which, when decoded with parquet-tools will contain a base64-encoded value:

```shell
> docker run --rm -v$(pwd):/tmp/parquet nathanhowell/parquet-tools cat /tmp/parquet/output.parquet
test = ZGVhZGJlZWY=
```

however, if we change [this](https://github.com/benthosdev/benthos/blob/ba4b1d13570756ac273774d1a2c4772fef18680a/internal/impl/parquet/processor_encode.go#L121) line of code to `n = parquet.String()`, then parquet-tools will output `test = deadbeef`.
