### ISSUE TITLE
NATS JetStream output not acknowledging delivered messages

### ISSUE THREAD

**Issue by davidandradeduarte** [redpanda-data/connect#1433]
Hi 👋 

I'm trying to use the [nats_jetstream](https://www.benthos.dev/docs/components/outputs/nats_jetstream/) output, but it seems like it's not acknowledging delivered messages.
This simple pipeline doesn't work for me:

```yaml
input:
  generate:
    mapping: root = {"test":"message","id":uuid_v4()}
    count: 5

output:
  nats_jetstream:
    urls:
      - nats://localhost:4222
    subject: foo
```

First 5 messages are delivered without any error, after that it keeps trying to deliver (this time with a timeout error) on an infinite loop.

I have a [repository with repro steps](https://github.com/davidandradeduarte/benthos-nats-jetstream-output-loop-bug), if you'd like to use it.
Not sure if I'm doing something wrong, as this is such a simple pipeline.
I've tried to have a look at how this output _ack's_ messages, but had no luck. Also looking at the integration tests for this output, it doesn't seem like it's sending anything to the input, it's just testing connectivity.

Anyway, hope anyone can help. 🤗
