### ISSUE TITLE
HTTP components cannot specify audience when using Oauth2

### ISSUE THREAD

**Issue by cristiprg** [redpanda-data/connect#1812]
Similar to this issue https://github.com/benthosdev/benthos/issues/917, I'm not able to authenticate an HTTP request using Oauth2 because I can't specify certain fields, namely `audience` and perhaps `grant_type`.

Would love if we could do something like this:

```
output:
  http_client:
    url: "http://some-url:8080/graphql"
    oauth2:
      enabled: true
      client_key: "AUTH0_CLIENT_ID"
      client_secret: "AUTH0_CLIENT_SECRET"
      token_url: "AUTH0_PROVIDER_ADDRESS"
      audience: "AUTH0_AUDIENCE" <-- new
      scopes: []
```

**Comment by rockwotj** [comment]
You can do this with `endpoint_params`

**Comment by rockwotj** [comment]
Auth0 example:

```
    - http:
        url: "example.com"
        timeout: 30s
        oauth2:
          enabled: true
          client_key: ${CLIENT_ID}
          client_secret: ${CLIENT_SECRET}
          token_url: https://integration-cloudv2.us.auth0.com/oauth/token
          endpoint_params:
            grant_type: ["client_credentials"]
            audience: ["cloudv2-ign.redpanda.cloud"]
```
