### ISSUE TITLE
Add detailed error log

### ISSUE THREAD

**Issue by margamraviteja** [redpanda-data/connect#1972]
```
config.yaml
input:
  generate:
    interval: ""
    mapping: "root = {}"
    count: 1

pipeline:
  processors:
    - mapping:
        import "logic/logic1.blob"
        import "logic/logic2.blob"
        let rand num = random int (seed: timestamp_ unix nano () , min: 20, max: 40)
        root = if ($rand num < 30) J
           this. apply ("logic1")
        } else (
           this. apply ("logic2")
        }

logic/logic1.yaml
map logic1 {
  root = this.logic1.slice (0, 5)
}

logic/logic2.yaml
map logic1 {
  root = this.logic1.slice (5, 10)
}
```

```
ERRO failed assignment (line 5): failed assignment (line 2): expected array or string value, got null from field this. logic1
```

I have different *.blobl files, which I’m importing and then if I got any exception, it’s showing some field got null or expected array or string with line number (I may refer the same field name in multiple mappings) but not exactly in which mappings - which is difficult to find where exactly the issue is.

![IMG_5082](https://github.com/benthosdev/benthos/assets/10586267/83cd2c1f-369d-439b-9042-76656f40ca05)

**Comment by mihaitodor** [comment]
Simple way to reproduce:

`foo.blobl`:
```coffee
map foo {
  root = this.foo | throw("Kaboom!")
}
```
`bar.blobl`:
```coffee
map bar {
  root = this.bar | throw("Kaboom!")
}
```

`benthos.yaml`:
```yaml
input:
  generate:
    count: 2
    mapping: root.map = if count("test") == 1 { "foo" } else { "bar" }
    interval: 0s
  processors:
    - mapping: |
        import "./foo.blobl"
        import "./bar.blobl"
        root = this.apply(this.map)
```

```shell
> benthos -c benthos.yaml
INFO Running main config from specified file       @service=benthos path=benthos.yaml
INFO Listening for HTTP requests at: http://0.0.0.0:4195  @service=benthos
INFO Launching a benthos instance, use CTRL+C to close  @service=benthos
ERRO failed assignment (line 3): failed assignment (line 2): Kaboom!  @service=benthos label="" path=root.input.processors.0
{"map":"foo"}
ERRO failed assignment (line 3): failed assignment (line 2): Kaboom!  @service=benthos label="" path=root.input.processors.0
{"map":"bar"}
```
Note that the 2 error logs are identical. I think it would help to have `apply()` inject the map name as an annotation in them.
