### ISSUE TITLE
Memory cache never compacts expired keys with a stable set of cache keys

### ISSUE THREAD

**Issue by dudleycarr** [redpanda-data/connect#1993]
We're using Benthos to periodically monitor and process a set of IDs. To prevent needless reprocessing, we're caching IDs for some period of time. If the ID wasn't successfully processed downstream after the cache key TTL, we expect the ID to have been purged from the cache and be reprocessed.

Minimal configuration:
```yaml
input:
  generate:
    interval: 1s
    mapping: root.key = "a"
pipeline:
  threads: -1
  processors:
    - cache:
        resource: mycache
        operator: add
        key: '${! json("key") }'
        value: "foo"
        ttl: 10s
    - mapping: root = if errored() { deleted() }
output:
  label: ""
  stdout:
    codec: lines
cache_resources:
  - label: mycache
    memory:
      compaction_interval: 1s
```

Expected output after 10s
```json
{"key":"a"}
{"key":"a"}
```

Actual output after 10s
```json
{"key":"a"}
```

The current work around is to always set a key on each pass through the pipeline to force a compaction for expired cache entries.
