### ISSUE TITLE
SFTP input - last file not deleted

### ISSUE THREAD

**Issue by joffreychambrin** [redpanda-data/connect#2435]
Hi 👋 

I have discovered an issue when the sftp input component is configured with watcher enabled and delete_on_finish enabled. 

Steps to reproduce:
- Upload 10 files to the SFTP
- Run the benthos pipeline (see below for config)
- After the files have been consumed by the pipeline, check the SFTP => one file is still there even if it has been consumed by benthos.

Here is the configuration file I am using
```yaml
cache_resources:
  - label: memory
    memory:
      default_ttl: 5m
      compaction_interval: 60s
      init_values: {}

input:
  sftp:
    address: ${SFTP_HOST}
    credentials:
      username: ${SFTP_USERNAME}
      password: ${SFTP_PASSWORD}
    paths:
      - "folder/**"
    scanner:
      to_the_end: {}
    delete_on_finish: true
    watcher:
      enabled: true
      minimum_age: 1s
      poll_interval: 20ms
      cache: memory

pipeline:
  processors:
    - log:
        level: INFO
        message: "message received"

output:
  label: ""
  stdout:
    codec: lines
```
