### ISSUE TITLE
Output resources connects even if unused

### ISSUE THREAD

**Issue by alessandro-gomma** [redpanda-data/connect#2523]
Hi!

while building our streams we tried to avoid code duplication by replacing our outputs with a resource. 
While trying different configurations, we noticed that if we declare multiple output resources, they immediately connect upon startup even if these resources aren't referenced in any stream.

Here's our resource.yaml file:

``` yaml
output_resources:
  - label: "first_output"
    nats:
      urls: ["nats://127.0.0.1:1234"]
      subject: ${! @output_subject }
  - label: "second_output"
    nats:
      urls: ["nats://127.0.0.1:5678"]
      subject: ${! @output_subject }
```

Here's the stream file:

``` yaml
input:
  broker:
    inputs:
      [...]

pipeline:
  processors:
    [...]

output:
  label: output
  resource: "first_output"
```

And this is the startup script:
``` bash
benthos  -e "config.env" -c "./common/common.yaml" -r "./resources/*.yaml" -t "./templates/*.yaml" streams "./config/*.yaml"
```

In our solution, we would like to define multiple output resources in a single yaml file. Since we plan to have plenty of different outputs in the same file, we want to be sure that only the referenced resources are actually instantiated.
Is there any way to avoid the "second_output" resource to be used when not referenced? (e.g. lazy loading?)

**Comment by kmpm** [comment]
I have the same issue but with inputs and nats, so lazy loading would be beneficial even there.

**Comment by artemklevtsov** [comment]
The same issue with kafka_franz outputs.

**Comment by artemklevtsov** [comment]
As workaround I build the final standalone config without resources.

```
input:
  {{ include "in_enum_file.yaml.tpl" | indent 2 | trim }}

pipeline:
  processors:
    - {{ include "proc_skip_empty_lines.yaml.tpl" | indent 6 | trim }}
    - {{ include "proc_enum_payload.yaml.tpl" | indent 6 | trim }}
    - {{ include "proc_misc_payload.yaml.tpl" | indent 6 | trim }}
    - {{ include "proc_log_payload.yaml.tpl" | indent 6 | trim }}

output:
  # stdout: {}
  switch:
    cases:
      - check: errored()
        output:
          fallback:
            - {{ include "out_error_clickhouse.yaml.tpl" | indent 14 | trim }}
            - {{ include "out_error_kafka.yaml.tpl" | indent 14 | trim }}
      - output:
          fallback:
            - {{ include "out_enum_clickhouse.yaml.tpl" | indent 14 | trim }}
            - {{ include "out_error_clickhouse.yaml.tpl" | indent 14 | trim }}
            - {{ include "out_error_kafka.yaml.tpl" | indent 14 | trim }}
```

Render with https://github.com/coveooss/gotemplate
