### ISSUE TITLE
[Feature Request] Trim whitespaces from columns in CSV scanner/input

### ISSUE THREAD

**Issue by nerstak** [redpanda-data/connect#2613]
Hi!

It would be useful to be able to trim whitespaces from CSV, similar to the `trimColumn` parameter in [File Pulse (Kafka Connector)](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#delimitedrowfilter).

Something similar to this:
```yaml
csv:
  custom_delimiter: ","
  parse_header_row: true
  trim_whitespaces_header_row: true
```

It would be able to process headers with whitespaces within, such that the following csv:
```
a ,b ,c 
a1,b1,c1
```
would be process as `{"a":"a1","b":"b1","c":"c1"}` instead of `{"a ":"a1","b ":"b1","c ":"c1"}` (current behavior).

Regards.
