### ISSUE TITLE
S3 output missing header since aws-sdk-go-v2 upgrade

### ISSUE THREAD

**Issue by dom-lee-naimuri** [redpanda-data/connect#2687]
Hi, I've recently attempted to upgrade from v4.24.0, but encountered an issue with how the S3 output behaves when writing to a bucket with object lock enabled.

Using Benthos with versions greater than 4.24.0, AWS rejects the PutObject request with error: "Content-MD5 OR x-amz-checksum- HTTP header is required for Put Object requests with Object Lock parameters".

I believe this is due to the switch to `aws-sdk-go-v2` [which occurred in v4.25.0](https://github.com/redpanda-data/connect/blob/main/CHANGELOG.md#4250---2024-03-01). I'm not very familiar with Go, but I've had a look through the code for `aws-sdk-go`, and it looks like the original version of the SDK would automatically set the `Content-MD5` header for each `PutObject` request. See [here](https://github.com/aws/aws-sdk-go/blob/main/service/s3/customizations.go#L56) and [here](https://github.com/aws/aws-sdk-go/blob/main/service/s3/body_hash.go#L80).

I don't expect the Benthos connector to derive the MD5 and apply it automatically like the old `aws-sdk-go` did, but would like a way to provide it to the output e.g.:

```
      aws_s3:
          bucket: ingest-prod-data
          path: ${! meta("write_path") }
          tags: {}
          region: eu-west-2
          content_type: application/octet-stream
          content_md5: $!{ meta("file_hash") }
``` 

I'd be grateful if someone could check my assumptions regarding the `aws-sdk-go` to make sure I'm reading it right, and for alternative suggestions for how to fix this, whether it needs to be fixed or we can work around it somehow.

Thanks

**Comment by mihaitodor** [comment]
Hey @dom-lee-naimuri 👋 As a workaround, would you mind trying to attach a `mapping` processor to that `aws_s3` output with `meta Content-MD5 = metadata("file_hash")`? Details here: https://docs.redpanda.com/redpanda-connect/components/outputs/aws_s3/#metadata-2. We can also add an extra field to the output if that's easier. PRs are welcome.

**Comment by dom-lee-naimuri** [comment]
Hi @mihaitodor, thanks for this suggestion. I've done the following to test:

```
pipeline:
  processors:
    - mapping: |-
        meta "Content-MD5" = "value"
        meta mykey = "another value"


output:
  processors:
    - log:
          level: INFO
          message: '${! meta("Content-MD5") }'
  aws_s3:
    bucket: 'bucket-name'
    path: 'doms-test-file'
    tags: {}
    region: eu-west-2
    content_type: application/octet-stream

```

Unfortunately before being sent off in the request, metadata keys are prefixed with `x-amz-meta` and stored as user defined metadata in S3. I'll raise a PR to add `Content-MD5` to the S3 output when I get a chance
