### ISSUE TITLE
error() and errored() The expected result is not returned

### ISSUE THREAD

**Issue by JuchangGit** [redpanda-data/connect#2750]
redpanda-connect_4.30.1
配置:
```
http:
  enabled: false
  
input:
  sql_raw:
    driver: oracle
    dsn: oracle://BPM_TEST:Hzsun.com!2@192.168.2.15:1521/ORCLPDB1
    query: |
      SELECT A1,B1,C,D FROM TEST1

pipeline:
  processors:
    - mapping:
        root.D = this.D.int64()
    - branch:
          request_map: |
            root = this
          processors:
            - log: 
                level: TRACE
                message: '777 ${! content() } ${! error() } ${! errored() }'           
          result_map: 'root = "0"'
    
output:
  file:
    path: data.txt
    codec: lines
    
logger:
  level: ALL
```
执行结果:
![image](https://github.com/user-attachments/assets/563061d1-b1f5-4d7c-b03d-805ba85e7a64)
