### ISSUE TITLE
How to using parquet_encode the data from parquet_decode

### ISSUE THREAD

**Issue by fearfate** [redpanda-data/connect#2773]
I try to sync the parquet encoded data from gcs and do some process to it, then write them back to the parquet encoded file in local, got two problem to finish that, my stream config look like:

```yaml
input:
  label: "bigquery_package_versions"
  sequence:
    inputs:
    - gcp_bigquery_select:
        project: example
        table: bigquery-public-data.deps_dev_v1.PackageVersions
        columns:
        - "*"
        where:  SnapshotAt >= ? AND SnapshotAt < ? # No default (optional)
        auto_replay_nacks: true
        # job_labels: {}
        # priority: ""
        args_mapping: |
          root = ["2024-08-05", "2024-08-11"]
        prefix: |
          EXPORT DATA OPTIONS(
            uri='gs://ysdb/package_versions/2024-08-05/*.parquet',
            format='parquet',
            compression='zstd',
            overwrite=true) AS
        suffix: |
          ORDER BY System asc, Name asc
    - gcp_cloud_storage:
        bucket: ysdb
        prefix: package_versions
        delete_objects: true

pipeline:
  processors:
    - parquet_decode: {}
    - for_each:
      - mapping: |
          #!blobl
          root = this
          root.ID = root.Purl
          root.SnapshotAt = root.SnapshotAt.ts_unix_nano()
          if root.exists("UpstreamPublishedAt") && root.UpstreamPublishedAt != null {
            root.UpstreamPublishedAt = root.UpstreamPublishedAt.ts_unix_nano()
          }
          meta SnapshotAt = root.SnapshotAt

    - parquet_encode:
        schema:
        - name: SnapshotAt
          type: INT64
        - name: System
          type: UTF8
        - name: Name
          type: UTF8
        - name: Version
          type: UTF8
        - name: Licenses
          type: UTF8
          repeated: true
        - name: Links
          repeated: true
          fields:
            - name: Label
              type: UTF8
            - name: URL
              type: UTF8
        - name: Advisories
          repeated: true
          fields:
            - name: Source
              type: UTF8
            - name: SourceID
              type: UTF8
        - name: VersionInfo
          optional: true
          fields:
            - name: IsRelease
              type: BOOLEAN
            - name: Ordinal
              type: INT64
        - name: Hashes
          repeated: true
          fields:
            - name: Type
              type: UTF8
            - name: Hash
              type: UTF8
        - name: DependenciesProcessed
          optional: true
          type: BOOLEAN
        - name: DependencyError
          optional: true
          type: BOOLEAN
        - name: UpstreamPublishedAt
          optional: true
          type: INT64
        - name: Registries
          type: UTF8
          repeated: true
        - name: SLSAProvenance
          optional: true
          fields:
            - name: SourceRepository
              type: UTF8
            - name: Commit
              type: UTF8
            - name: URL
              type: UTF8
            - name: Verified
              type: BOOLEAN
        - name: UpstreamIdentifiers
          repeated: true
          fields:
            - name: PackageName
              optional: true
              type: UTF8
            - name: VersionString
              optional: true
              type: UTF8
            - name: Source
              type: UTF8
        - name: Purl
          type: UTF8
        default_compression: zstd

output:
  file:
    path: ${! timestamp_unix_nano() }.parquet
    codec: all-bytes
```

1. the data `parquet_decode` produced can't be encoded by `parquet_decode` for the schema is not worked, the final result was encoded not expectly
2. `for_each` splited the batches one by one, and there's no processor like `broker` or `batch` to collect them together

Was it my mistake to use them incorrectly?
