### ISSUE TITLE
Pipeline that exit quickly do not always flush logs to redpanda topic

### ISSUE THREAD

**Issue by gavinheavyside** [redpanda-data/connect#2788]
Quick-running pipelines that complete and exit can do so before logs are flushed to redpanda topics. 

example, for a small table with only a few rows:
```
input:
  sql_select:
    driver: "mysql"
    dsn: <url to mysql DB>
    table: <table name>
    columns:
      - '*'
    auto_replay_nacks: true

pipeline:
  threads: -1
  processors: []

output:
  kafka_franz:
    seed_brokers: [ '<seed brokers url>']
    topic: "<topic name>"
    tls:
      enabled: true
    sasl:
      - mechanism: SCRAM-SHA-256
        username: <username>
        password: <password>
```

The pipeline populates the output topic, but no redpanda logs are seen. In the scenario where the pipeline exits with a nonzero error code, we would also want error logs for context
