### ISSUE TITLE
Blob file from input_resource are not removed with "delete_objects: true"

### ISSUE THREAD

**Issue by tifennlegoff** [redpanda-data/connect#2802]
Hi, we're using Azure Blob Storage with target input from Azure Queue Storage as input and a Kafka topic as output.
We observe that even after doc processed, they are not removed from Blob storage.

We have this input resource

```yaml
input_resources:
  - label: main
    azure_blob_storage:
      storage_connection_string: ${AZURE_STORAGE_CONNECTION_STRING}
      container: ${AZURE_CONTAINER}
      delete_objects: ${AZURE_STORAGE_INPUT_DELETE_OBJECT:true}
      prefix: "replay/"
      scanner:
        to_the_end: {}
      targets_input:
        azure_queue_storage:
          storage_connection_string: ${AZURE_STORAGE_CONNECTION_STRING}
          queue_name: ${AZURE_QUEUE_IN}
          dequeue_visibility_timeout: ${AZURE_DEQUEUE_TIMEOUT:30s}
          max_in_flight: ${AZURE_QUEUE_MAX_IN_FLIGHT:1}
          track_properties: false
        processors:
          - mapping: |-
              let json = content().decode("base64").parse_json()
              if $json.eventType == "Microsoft.Storage.BlobCreated" {
                root.name = $json.data.url.parse_url().path.trim_prefix("/" + env("AZURE_CONTAINER") + "/")
              } else {
                root = deleted()
              }

```

In logs (in debug), I see that doc is processed and well present in our output
```json
{"@service":"xxx","@system":"xxx","blob_prefix":"xxx","delay_until":1724343507,"dlq_attempt":1,"documentId":"xxx","label":"","level":"debug","msg":"Processing document: xxx from pipeline: xxx","path":"root.pipeline.processors.4","retry_topic":"xxx","time":"2024-08-22T16:18:27Z"}
```

But the doc is still present in the Blob storage and debug don't show any error about deletion. Do we miss something?

Thanks!
