### ISSUE TITLE
CSV Scanner not working in SFTP context : extraneous or missing \" in quoted-field"

### ISSUE THREAD

**Issue by acornforth** [redpanda-data/connect#2812]
Tested with the same files locally using the csv input, works fine. Something about the records extracted from the csv is breaking when they are pulled from sftp. Not sure is this is something speicif to the SFTP server we are connecting to.

I have already googled for issues, and a found some instance of this error occurring for example when line endings are /r, not /r/n or /n. but i checked this and it doesn't appear to be the cause in our case.

Not sure if this is a benthos issue directly or something to do with the underlying encoding/csv package

config below:

```
input:
  sftp:
    address: '${SFTP_HOST}:22'
    credentials:
      username: '${SFTP_USER}'
      password: '${SFTP_PASSWORD}'
      private_key_file: '/app/.ssh/id_rsa'
    paths:
      - '/*.csv'
    auto_replay_nacks: true
    scanner:
      csv:
        - parse_header_row: true
    delete_on_finish: false
    watcher:
      enabled: true
      minimum_age: 20s
      poll_interval: 60s
      cache: memory

buffer:
  none: {}
output:
  stdout: {}

cache_resources:
  - label: memory
    memory:
      default_ttl: 7200s
  - label: redis
    redis:
      url: 'redis://${REDIS_HOST}:${REDIS_PORT}'
      prefix: benthos_sftpw_cache_

```

**Comment by mihaitodor** [comment]
Hey @acornforth 👋 Thanks for reporting this! Would you mind doing a quick test and set [`lazy_quotes: true`](https://docs.redpanda.com/redpanda-connect/components/scanners/csv/#lazy_quotes) in the `csv` scanner? It should look like this (not sure why you had it as an array):
```yaml
scanner:
      csv:
         parse_header_row: true
         lazy_quotes: true
```

I think the error you're hitting is due to [this code](https://cs.opensource.google/go/go/+/refs/tags/go1.23.0:src/encoding/csv/reader.go;l=399-406) in the parser.

PS: Converting to a discussion as per #2026.
