### ISSUE TITLE
Add support for `EmitDefaultValues` in `protobuf` processor

### ISSUE THREAD

**Issue by szymonorz** [redpanda-data/connect#2884]
As of now `protobuf` processor doesn't have an ability to emit default values from protobuf messages.

Meaning, given schema:

```proto
syntax = "proto3";
package prototest;
option go_package = "github.com/szymonorz/genserver";

message Event {
	string id = 1;
	int64 timestamp = 2;
	string name = 3;
	bool approved = 4;
}
```

if `approved` was set to `false` (`bool` default value) then after converting the event to JSON, that field would be omitted from message.

```yaml
pipeline:
  processors:
    - protobuf:
        operator: to_json
        message: prototest.Event
        import_paths: [./schema]
```
```json
{"id":"aaaaa", "timestamp":"1726777881", "name":"Robert"}
{"id":"aaaaa", "timestamp":"1726777881", "name":"Robert", "approved":true}
{"id":"aaaaa", "timestamp":"1726777881", "name":"Robert"}
{"id":"aaaaa", "timestamp":"1726777881", "name":"Robert", "approved":true}
{"id":"aaaaa", "timestamp":"1726777881", "name":"Robert"}
{"id":"aaaaa", "timestamp":"1726777881", "name":"Robert", "approved":true}
{"id":"aaaaa", "timestamp":"1726777881", "name":"Robert"}
```
 
`google.golang.com/protobuf` supports `EmitDefaultValues` in [protojson.MarshallOptions](https://pkg.go.dev/google.golang.org/protobuf@v1.34.2/encoding/protojson#MarshalOptions)

I think it would be a nice feature to have ability to enable it in Connect. I propose adding `emit_default_values` field to the processor. It should be disabled by default to not affect already existing pipelines

```yaml
pipeline:
  processors:
    - protobuf:
        operator: to_json
        message: prototest.Event
        import_paths: [./schema]
        emit_default_values : true
```

```json
{"id":"aaaaa", "timestamp":"1726777564", "name":"Robert", "approved":false}
{"id":"aaaaa", "timestamp":"1726777564", "name":"Robert", "approved":true}
{"id":"aaaaa", "timestamp":"1726777564", "name":"Robert", "approved":false}
{"id":"aaaaa", "timestamp":"1726777564", "name":"Robert", "approved":false}
{"id":"aaaaa", "timestamp":"1726777564", "name":"Robert", "approved":true}
```

I'm willing to implement this if you are ok with having this feature
