### ISSUE TITLE
[input_mongodb] Bloblang query is not working with ISODate field

### ISSUE THREAD

**Issue by lytuan99** [redpanda-data/connect#2889]
#### I've tried many ways in configuring input below, all of those command can not get data.

```yml
    query: |
      root.createdAt = {"$lte": now()}
## in history queries mongodb: "$lte": "2024-09-22T08:58:00.139917+07:00"
##
    query: |
      root.createdAt = {"$lte": timestamp_unix() - 90 * 86400}
## in history queries mongodb: "$lte": new NumberInt("1597405526")
##
    query: |
      root.createdAt = {"$gte": (timestamp_unix() - 90 * 86400).ts_format()}
## in history queries mongodb: "$gte": "2024-06-24T08:58:55+07:00"
## .....
```

#### In my IDE, I execute the query below, and it works.
```js
db.orders.find({
  createdAt: {
    $gte: new Date("2024-02-02"),
  },
});
```
![image](https://github.com/user-attachments/assets/8688caa1-9914-4ddb-b87a-863931a53f17)

Did I missing something or the RedPanda-connect should add a new feature for ISODate object?
