### ISSUE TITLE
sqlite3 cache reading re-reading existing files that are in the cache on Connector Restart.

### ISSUE THREAD

**Issue by alextreichler** [redpanda-data/connect#2901]
**Issue**
The following YAML below monitors an SFTP and when a new file is added it reads the file contents to stdout. However, when I restart the redpanda connect service, it reads all the files in the SFTP again - even though they are processed already and in the cache (sqlite3).

**Expected behavior:**
When redpanda connect is restarted, it should not process the file again that have already been processed in the SFTP as they exist inside the cache.

Sample Yaml

```
input:
  sftp:
    address: "0.0.0.0:2200"
    credentials:
      username: "foo"
      password: "pass"
    paths:
      - /products/*.csv
    scanner:
      csv:
        custom_delimiter: "|"
        parse_header_row: true
        continue_on_error: false
    watcher:
      enabled: true
      cache: "sql"

output:
  stdout: {}
cache_resources: # []
  - label: "sql"
    sql:
      driver: "sqlite"
      dsn: file:/dir/to/database/file/my.db
      table: sftp_cache
      key_column: foo
      value_column: bar
```
