### ISSUE TITLE
[`javascript` processor] Update `goja` packages to the latest versions

### ISSUE THREAD

**Issue by heikkilamarko** [redpanda-data/connect#2910]
Hi, I tried using the `Math.js` (https://mathjs.org/) library in the `javascript` processor:
```yaml
input:
  generate:
    mapping: |
      root.a = [[1, 2], [3, 4]] 
      root.b = [[5, 6], [1, 1]]
    count: 10
    interval: ""

pipeline:
  processors:
    - javascript:
        code: |
          function run() {
            const math = require("mathjs")
            const root = benthos.v0_msg_as_structured()
            root.result = math.multiply(root.a, root.b)
          }
          run();
output:
  file:
    path: out.json

logger:
  level: DEBUG
```
However, this gave me an error because the `goja` version that Redpanda Connect is using is outdated and does not support `BigInt`. I created a custom build where I updated the `goja` and `goja_nodejs` packages to the latest version, and the pipeline started to work.

<img width="1659" alt="Screenshot 2024-09-30 at 19 37 57" src="https://github.com/user-attachments/assets/a8dba9a1-8954-42cd-9547-b2e0dbbea5dc">

Is there any chance these packages could be updated, so that a custom build is no longer needed?
