### ISSUE TITLE
file cache should be able to create directories

### ISSUE THREAD

**Issue by trashhalo** [redpanda-data/connect#2932]
if you put a `/` in your cache key today file cache errors `ERRO failed to write result to cache: %!s(<nil>)   @service=redpanda-connect label="" path=root.pipeline.processors.0.branch.processors.0`. It would be helpful if it did not error because then file could mimic object stores like s3 for local development.

**Comment by trashhalo** [comment]
I also tried:
```
cache_resources:
  - label: file_cache
    file:
      directory: /cache${! meta("X-Tenant-Id") }
```
but that had the same error.
