### ISSUE TITLE
gcp_pubsub output: not recovering from failures when ordering key is enabled 

### ISSUE THREAD

**Issue by erdody** [redpanda-data/connect#2935]
# Scenario

A gcp_pubsub connector (v4.37.0) configured something like this:

```yaml
input:
  kafka: # btw, this is why we can't move to kafka_franz: https://github.com/redpanda-data/connect/issues/2745
    addresses: [ localhost:19092 ]
    topics: [ ordered-topic ]
    consumer_group: ordered-cg
    checkpoint_limit: 1 # https://docs.redpanda.com/redpanda-connect/components/inputs/kafka/#ordering
    batching:
      count: 100
      period: 1s
output:
  gcp_pubsub:
    project: <redacted>
    credentials: <redacted>
    topic: ordered-topic
    ordering_key: ordering-key
```

# Expectation

After, for example, an internet interruption, the connector should automatically recover and resume publishing.

# What we see

The connector does not auto-recover, and keeps failing with:

```
{"@service":"redpanda-connect","label":"","level":"error","msg":"Failed to send message to gcp_pubsub: pubsub: Publishing for ordering key, ordering-key, paused due to previous error. Call topic.ResumePublish(orderingKey) before resuming publishing","path":"root.output","stream":"stream-pubsub"}
```

you have to restart the process to restore the flow.

It looks like a call to [topic.ResumePublish](https://cloud.google.com/pubsub/docs/samples/pubsub-resume-publish-with-ordering-keys) is missing, either after a failure or before each batch.
