### ISSUE TITLE
Both `kafka_franz` and `kafka` inputs emit the `kafka_key` metadata as string, but `bytes` should be used instead

### ISSUE THREAD

**Issue by mihaitodor** [redpanda-data/connect#2954]
Run either the `kafka_franz` or the `kafka` output to produce 2 messages. For the first one, set `key: ""` and for the second one, do not set this field.

Now, try running this config:

```
input:
  kafka:
    ...

output:
  stdout: {}
  processors:
    - mapping:
        root = metadata("kafka_key").format_json()
```

Note that for both messages the output is `""` and I can't think of any way to distinguish between them.

As far as I can tell, we allow implicit conversion from bytes to string, so maybe we can just get rid of the string cast [here](https://github.com/redpanda-data/connect/blob/5b508db885bd35976a78edb331cf4bc4b402a74a/internal/impl/kafka/input_kafka_franz.go#L291) and [here](https://github.com/redpanda-data/connect/blob/5b508db885bd35976a78edb331cf4bc4b402a74a/internal/impl/kafka/input_sarama_kafka.go#L415) since we now have [structured metadata](https://github.com/redpanda-data/connect/issues/1558)...
