### ISSUE TITLE
Env vars are not read anymore starting with 4.39.0

### ISSUE THREAD

**Issue by venatir** [redpanda-data/connect#2992]
How to replicate:

Here's a sample file to test

```
input:
  type: stdin
pipeline:
  processors:
    - log:
        level: info
        message: "DB_CONNECTION_URL: ${DB_CONNECTION_URL}"
output:
  type: stdout
```

1. set the test env var and running this in 4.38.0. - works
2. set the test env var and running this in 4.39.0. - complains about missing env var.

This has been tested in the 4.38.0 and 4.39.0 tags for docker - redpandadata/connect in repository dockerhub
