### ISSUE TITLE
http_server: Not receiving Websocket messages

### ISSUE THREAD

**Issue by erikuusitalo** [redpanda-data/connect#2997]
When initially connecting, everything works as expected. However, upon reconnection, message handling becomes inconsistent. Sometimes messages are delivered, but this is very random, and often the reconnection fails entirely.

In some cases, the following warning appears in the logs:

```
WARN Failed to send message: write tcp 172.25.0.8:4195->172.25.0.1:57554: write: broken pipe  @service=redpanda-connect label="" path=root.output
```

![image](https://github.com/user-attachments/assets/533af07b-ec59-40fd-9f58-293b300f7a01)

Running config:

```
logger:
  level: ALL
  format: logfmt
  add_timestamp: false
  static_fields:
    '@service': redpanda-connect
input:
  kafka:
    addresses: ["redpanda:9092"] # No default (required)
    topics: ["TEST"] # No default (required)
    target_version: 2.1.0 # No default (optional)
    consumer_group: "test"
    checkpoint_limit: 1024
    auto_replay_nacks: true
buffer:
  none: {}
pipeline:
  threads: -1
  processors: []
output:
  broker:
    pattern: fan_out
    outputs:
    - stdout: {}
    # - kafka:
    #     addresses: ["redpanda:9092"] # No default (required)
    #     topic: "OUTPUT" # No default (required)
    - http_server:
        ws_path: /get/ws
        allowed_verbs:
          - GET
```
Any guidance or suggestions on how to resolve this issue would be greatly appreciated.
