### ISSUE TITLE
Authenticating with a token and user/pass in NATS JetStream resources 

### ISSUE THREAD

**Issue by ghstahl** [redpanda-data/connect#3010]
should be part of this old [one](https://github.com/redpanda-data/connect/issues/859)

Nats [connecting by token](https://docs.nats.io/using-nats/developer/connecting/token)  
```go
// Set a token
nc, err := nats.Connect("127.0.0.1", nats.Name("API Token Example"), nats.Token("mytoken"))
if err != nil {
    log.Fatal(err)
}
defer nc.Close()

// Do something with the connection
```
[Current](https://docs.redpanda.com/redpanda-connect/components/inputs/nats_jetstream/?tab=tabs-1-advanced)
```
 auth:
      nkey_file: ./seed.nk # No default (optional)
      nkey: "" # No default (optional)
      user_credentials_file: ./user.creds # No default (optional)
      user_jwt: "" # No default (optional)
      user_nkey_seed: "" # No default (optional)
```

I am currently using a token to connect which is handled by our AuthCallout.
