### ISSUE TITLE
input `parquet` got decoding panic

### ISSUE THREAD

**Issue by fearfate** [redpanda-data/connect#3091]
config:

```yaml
input:
  parquet:
    paths:
      - '*.parquet'
    auto_replay_nacks: false
    # batch_count: 0

output:
  drop: {}
```

run process like this:

![image](https://github.com/user-attachments/assets/890b1f98-5850-45ba-bc3f-644c27bb38d4)

the parquet file:

[example.zip](https://github.com/user-attachments/files/18176561/example.zip)
