### ISSUE TITLE
rpk adds "Downloading latest Redpanda Connect" as the first line of the generated yaml file

### ISSUE THREAD

**Issue by amrlafi** [redpanda-data/connect#3101]
Affected version: rpk version v24.3.2 (rev 32a9dce321) 
Environment: Mac (M1), installed via Homebrew. 

```yml
Downloading latest Redpanda Connect
http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /benthos
  debug_endpoints: false
  cert_file: ""
  key_file: ""
  cors:
    enabled: false
    allowed_origins: []
  basic_auth:
    enabled: false
    realm: restricted
    username: ""
    password_hash: ""
    algorithm: sha256
    salt: ""
input:
  stdin: {}
buffer:
  none: {}
pipeline:
  threads: -1
  processors: []
output:
  stdout: {}
input_resources: []
processor_resources: []
output_resources: []
cache_resources: []
rate_limit_resources: []
logger:
  level: INFO
  format: logfmt
  add_timestamp: false
  level_name: level
  timestamp_name: time
  message_name: msg
  static_fields:
    '@service': redpanda-connect
  file:
    path: ""
    rotate: false
    rotate_max_age_days: 0
metrics:
  prometheus: {}
  mapping: ""
tracer:
  none: {}
shutdown_delay: 0s
shutdown_timeout: 20s
tests: []
redpanda:
  seed_brokers: []
  client_id: benthos
  tls:
    enabled: false
    skip_cert_verify: false
    enable_renegotiation: false
    root_cas: ""
    root_cas_file: ""
    client_certs: []
  sasl: []
  metadata_max_age: 5m
  pipeline_id: ""
  logs_topic: ""
  logs_level: info
  status_topic: ""
  idempotent_write: true
  timeout: 10s
  max_message_bytes: 1MB
  broker_write_max_bytes: 100MB


```
