### ISSUE TITLE
parse_csv method failed with quoted header

### ISSUE THREAD

**Issue by artemklevtsov** [redpanda-data/connect#3157]
Working example:

<details>

Input:

```csv
col1,col2
val1,val2
val3,val4
```

Output:

```json
{"col1":"val1","col2":"val2"}
{"col1":"val3","col2":"val4"}
```
</details>

Not working example:

<details>

Input:

```csv
"col1","col2"
val1,val2
val3,val4
```

Output:

```
ERRO failed assignment (line 1): function content: parse error on line 1, column 4: bare " in non-quoted-field  @service=redpanda-connect label="" path=root.pipeline.processors.0
ERRO Failed to unarchive message part: failed to parse message into JSON array: invalid character 'ï' looking for beginning of value  @service=redpanda-connect label="" path=root.pipeline.processors.1
"col1","col2"
val1,val2
val3,val4
```

</details>

Config:

```yaml
logger:
  level: warn

input:
  file:
    paths:
      - out.csv
    scanner:
      to_the_end: {}

pipeline:
  processors:
    - mapping: |
        root = content().parse_csv()
    - unarchive:
        format: json_array

output:
  stdout: {}
```

rpk connect version is 4.44.0.

**Comment by ooesili** [comment]
Hi. I just ran the example you posted locally and it worked as expected:
```json
{"col1":"val1","col2":"val2"}
{"col1":"val3","col2":"val4"}

```
The error message `ERRO Failed to unarchive message part: failed to parse message into JSON array: invalid character 'ï' looking for beginning of value` makes me think there might be a strange non-printing byte sequence in your CSV file that's confusing connect. I check for that kind of stuff using `file` and `xxd`:
```
$ file out.csv
out.csv: ASCII text
$ xxd out.csv
00000000: 2263 6f6c 3122 2c22 636f 6c32 220a 2276  "col1","col2"."v
00000010: 616c 3122 2c22 7661 6c32 220a 2276 616c  al1","val2"."val
00000020: 3322 2c22 7661 6c34 220a                 3","val4".
```

**Comment by artemklevtsov** [comment]
Seems BOM is reason:

```bash
❯ file out.csv
out.csv: Unicode text, UTF-8 (with BOM) text
❯ xxd out.csv
00000000: efbb bf22 636f 6c31 222c 2263 6f6c 3222  ..."col1","col2"
00000010: 0a22 7661 6c31 222c 2276 616c 3222 0a22  ."val1","val2"."
00000020: 7661 6c33 222c 2276 616c 3422 0a         val3","val4".
```

**Comment by artemklevtsov** [comment]
Copy content with empty file and it's ok.

**Comment by artemklevtsov** [comment]
In my real case I receive this CSV with http_client input.

**Comment by artemklevtsov** [comment]
Working config with skip BOM:

```yaml
logger:
  level: warn

input:
  file:
    paths:
      - out.csv
    scanner:
      to_the_end: {}

pipeline:
  processors:
    - mapping: |
        root = if content().slice(0, 3).encode("hex") == "efbbbf" {
          content().slice(3).parse_csv()
        } else {
          content().parse_csv()
        }
    - unarchive:
        format: json_array

output:
  stdout: {}
```
I think the `parse_csv` should skip BOM.

**Comment by ooesili** [comment]
There's a handy scanner for exactly that. This should take care of it
```
input:
  file:
    paths:
      - out.csv
    scanner:
      skip_bom:
        into:
          to_the_end: {}
```

**Comment by artemklevtsov** [comment]
Can I use it as processor for the http_client response?

**Comment by mihaitodor** [comment]
@artemklevtsov Try this:

```
input:
  file:
    paths:
      - test.txt

  processors:
    - mapping: |
       root = content().slice(3)

output:
  http_client:
    url: ...
```

[test.txt](https://github.com/user-attachments/files/18626853/test.txt)

```shell
$ file test.txt
test.txt: Unicode text, UTF-8 (with BOM) text
```
