### ISSUE TITLE
Coordination DynamoDB table cross AWS account

### ISSUE THREAD

**Issue by jreyeshdez** [redpanda-data/connect#3159]
I am currently running into a situation where I am deploying Redpanda Connect into an EKS cluster in AWS Account B, however it will be consuming data from kinesis located in an AWS Account A, resulting in below config:

```yaml 
config:
    input:
      label: "test_dev"
      aws_kinesis:
        streams:
          - "arn:aws:kinesis:us-east-1:1234567890:stream/test_dev"
        dynamodb:
          table: "arn:aws:dynamodb:us-east-1:987654321:table/redpanda_connect_dev"
          create: false
        checkpoint_limit: 1024
        auto_replay_nacks: true
        commit_period: 5s
        start_from_oldest: true
        region: "us-east-1"
        credentials:
          role: "arn:aws:iam::1234567890:role/test-dev-assumable-role"
        batching:
          count: 10
          period: "100ms"
    output:
      stdout: {}
```
Basically both the DynamoDB table and Redpanda Connect deployment is located in account B, however kinesis stream is located in account A

`level=error msg="Failed to connect to aws_kinesis: operation error DynamoDB: DescribeTable, https response error StatusCode: 400, RequestID: 1234, api error AccessDeniedException: User: arn:aws:sts::1234567890:assumed-role/test-dev-assumable-role/aws-go-sdk-1738246912474529951 is not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:us-east-1:987654321:table/redpanda_connect_dev because no resource-based policy allows the dynamodb:DescribeTable action" @service=redpanda-connect label=test_dev path=root.input`

This role `arn:aws:iam::1234567890:role/test-dev-assumable-role` has permissions to read kinesis from Account A, however it seems it is only using same role to get access to DynamoDB which isnt in the same account.
