### ISSUE TITLE
Corrupted fields with parse_json

### ISSUE THREAD

**Issue by artemklevtsov** [redpanda-data/connect#3264]
Hi,

Example for reproduce:

```yaml
logger:
  level: warn
  format: json

input:
  generate:
    count: 1
    mapping: |
      #!blobl
      root.id = "80B7BD8D890B8A1F11E6BBC1F7B009C6".decode("hex").string()

pipeline:
  processors:
    - mapping: |
        #!blobl
        root = this.format_json().parse_json()
        root._id = root.id.encode("hex")

output:
  stdout: {}
```

Results:

```sh
❯ rpk connect run tmp/test.yaml
{"_id":"efbfbdefbfbdefbfbdefbfbdefbfbd0befbfbd1f11efbfbdefbfbdefbfbdefbfbdefbfbd09efbfbd","id":"�����\u000b�\u001f\u0011�����\t�"}
```

More compact example:

```
let x = { "id": "80B7BD8D890B8A1F11E6BBC1F7B009C6".decode("hex").string() }
let y = $x.format_json().parse_json()
root = {"original": $x, "parsed": $y}
```

msgpack works correctly.

Reproduced with go json package: https://go.dev/play/p/K9ayP-Es7p7

**Comment by artemklevtsov** [comment]
Seems related with #2536.

**Comment by artemklevtsov** [comment]
This is a bug in the `parse_json`:

```yaml
logger:
  level: warn
  format: json

input:
  generate:
    count: 1
    mapping: |
      #!blobl
      root.id = "80B7BD8D890B8A1F11E6BBC1F7B009C6".decode("hex").string()
      root.code = "Текст"

pipeline:
  processors:
    - mapping: |
        #!blobl
        root = this.format_json().parse_json()

output:
  stdout: {}
```
