### ISSUE TITLE
No Error message when SFTP server shuts down while RedPanda Connect is running

### ISSUE THREAD

**Issue by TomLemsky** [redpanda-data/connect#3296]
**Summary:**
I have encountered this behavior that seems suboptimal: When an SFTP server that Redpanda Connect is connected to shuts down while Redpanda Connect is running, there is no error message in the logs. Just "Attempting to write 1 messages to 'sftp'." with no corresponding success message. It seems to just wait forever for an ACK from the SFTP server that will never come. 

I would like to see some kind of error so that our alerting can realize that there is a problem with the connection to the SFTP server. My proposed solution would be a timeout that throws an error if no answer from the SFTP server arrived within a certain time.

**Expected behavior:** 
There should appear an error message in the logs when the SFTP is no reachable anymore. (Like the "Failed to connect to sftp" error message I get when the SFTP server is already down during the startup of Redpanda Connect)

**Observed behavior:** 
No error message in the logs. Just "Attempting to write 1 messages to 'sftp'." with no corresponding success message.

**How to reproduce:**

* Start SFTP server (e.g. `docker run -p 2222:22 -d emberstack/sftp --name sftp`)
* Start RedPanda Connect script that continually writes to the server (`rpk connect run sftp_example.yaml`)
* Wait for a short time for Red Panda Connect to send the first message.
* Shut down SFTP server (`docker stop sftp`)
* Check the RedPanda Connect logs to see no error message

Here's an example yaml file I have tested with, but anything with an sftp output should work for testing.

```
input:
  generate:
    mapping: |
      root = counter()
    interval: 5s
    auto_replay_nacks: true
pipeline:
  processors:
  - log:
      level: INFO
      message: ${! content() }
output:
  sftp:
    address: "127.0.0.1:2222"
    path: "${! uuid_v4() }"
    credentials:
      username: "demo"
      password: "demo"
    max_in_flight: 64
logger:
  level: ALL
```
