### ISSUE TITLE
health check not indicating NATS connection problems

### ISSUE THREAD

**Issue by static-moonlight** [redpanda-data/connect#3311]
When the network connection between Redpanda Connect (RPC) and NATS gets separated for long enough, RPC starts to print these errors.

```
ERRO Failed to read message: nats: connection closed  @service=redpanda-connect label="" path=root.input
```

Meanwhile the `/ping` and `/ready` endpoint are happily reporting that everything is ok:

```
HTTP/1.1 200 OK
Date: Tue, 01 Apr 2025 18:42:32 GMT
Content-Length: 4
Content-Type: text/plain; charset=utf-8

pong
```

```
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 01 Apr 2025 18:42:33 GMT
Content-Length: 106

{"statuses":[{"label":"","path":"input","connected":true},{"label":"","path":"output","connected":true}]}
```

The process is alive, printing errors which nobody is going to read, and not doing anything anymore.

IMHO, that disqualifies these 2 endpoints pretty much for a liveness probe.

**Comment by josephwoodward** [comment]
Having had a little look into this it appears the input can reach this state due to incorrect handling of instances where the pull/fetch function call to the NATS client returns a `nats.ErrConnectionClosed` error. (This can be observed by starting the input then restarting/stopping the NATS Server - see below for how to reproduce this).

Upon getting disconnected from the server, the client eventually exceeds the `max_reconnects` value and starts returning a `nats.ErrConnectionClosed` error. During this point `Read` continues to attempt to fetch from NATS and because it's given up trying to reconnect the fetch call continues to return the aforementioned error. During this period the `/ready` endpoint reports that everything is fine as the input is stuck in the `Read` loop.

This appears to be similar to issue https://github.com/redpanda-data/connect/issues/3257.

I've started [working on a fix here](https://github.com/redpanda-data/connect/pull/3510).

To reproduce:

```yaml
input:
  label: ""
  nats_jetstream:
    urls: ["nats://0.0.0.0:4222"] # No default (required)
    queue: ""
    subject: "foo"
    durable: "" 
    stream: "my_stream"
    bind: false
    deliver: all

output:
  label: ""
  stdout:
    codec: lines
```


Launch NATS Server and connect to it using the NATS CLI:

```
docker run -p 4222:4222 -ti nats -js  

nats context set nats 

nats pub foo --count=10 --sleep 1s 'Hello World'
```
Create a stream (with `foo` being a subject)
```
nats stream add my_stream 
```
