### ISSUE TITLE
sftp input creating new connection per file

### ISSUE THREAD

**Issue by shivchelwa** [redpanda-data/connect#3383]
We are seeing an issue with sftp input. A new connection is created for each scanned file and the connection are not closed until the process is stopped. The sshd file descriptors are going up steadily on sftp server. 

Tried to reproduce this issue locally by setting up sftp server using jmcombs/sftp:alpine with docker-compose.
```
  sftp:
    image: jmcombs/sftp:alpine
    container_name: sftp
    ports:
      - "2222:22"
    command: [ "foo:pass:1001" ]
    volumes:
      - /Users/username/test/uploads:/home/foo/uploads 
```
Here are my test artifacts:

_redis.yaml_
```
cache_resources:
  - label: redis_sftp
    redis:
      url: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}
      prefix: "benthos:sftp:file:"
```
_sftp_test.yaml_
```
input:
  sftp:
    address: ${SFTP_ADDR:"localhost:2222"}
    credentials:
      username: ${SFTP_USER:foo}
      password: ${SFTP_PASS:pass}
    paths: [ ${SFTP_UPLOAD_DIR:/uploads/files/*.txt} ]
    scanner:
      to_the_end: {}
    watcher:
      enabled: true
      minimum_age: ${FILE_MINIMUM_AGE:1m}
      poll_interval: ${FILE_POLL_INTERVAL:15s}
      cache: redis_sftp
pipeline:
  processors:
  - try:
    - log:
        message: processing file ${! @sftp_path }
    - mapping: root = deleted()
```

The logs from pipelines and sftp server indicates a connection being opened per file.

> INFO Running without a main config file            @service=benthos benthos_version=v4.48.0
> INFO Listening for HTTP requests at: http://0.0.0.0:4195/  @service=benthos
> INFO Launching Benthos in streams mode, use CTRL+C to close  @service=benthos
> INFO Output type stdout is now active              @service=benthos label="" path=root.output stream=sftp_conn_test
> INFO Input type sftp is now active                 @service=benthos label="" path=root.input stream=sftp_conn_test
> INFO processing file /uploads/files/file1.txt      @service=benthos custom_source=true label="" path=root.pipeline.processors.0.try.0 stream=sftp_conn_test
> INFO processing file /uploads/files/file2.txt      @service=benthos custom_source=true label="" path=root.pipeline.processors.0.try.0 stream=sftp_conn_test
> INFO processing file /uploads/files/file3.txt      @service=benthos custom_source=true label="" path=root.pipeline.processors.0.try.0 stream=sftp_conn_test

sftp server logs(docker)

> 2025-04-30 16:41:55 Accepted password for foo from 172.20.0.1 port 64430 ssh2
> 2025-04-30 16:46:05 Accepted password for foo from 172.20.0.1 port 60980 ssh2
> 2025-04-30 16:46:25 Accepted password for foo from 172.20.0.1 port 60440 ssh2
> 2025-04-30 16:46:42 Accepted password for foo from 172.20.0.1 port 57648 ssh2
> 2025-04-30 16:51:24 Connection closed by 172.20.0.1 port 64430
> 2025-04-30 16:51:24 Connection closed by 172.20.0.1 port 57648
> 2025-04-30 16:51:24 Connection closed by 172.20.0.1 port 60980
> 2025-04-30 16:51:24 Connection closed by 172.20.0.1 port 60440
