### ISSUE TITLE
TLS certificate error for Self Signed Schema Registry with schema_registry_decode

### ISSUE THREAD

**Issue by harishvashistha** [redpanda-data/connect#3440]
Hi Team,

I have been using earlier named Benthos with docker image **jeffail/benthos:4.17.0** for my pipeline which reads Avro messages from Kafka, then process them using **schema_registry_decode** for Avro to Json conversion to ultimately write to Standard output.

But once I migrated to Redpanda-connect docker image: **docker.redpanda.com/redpandadata/connect**. I have started getting TLS error while connecting to Self Signed Schema Registry even though I am providing TLS configuration for this processor:

**error**:

` tls: failed to verify certificate: x509: certificate signed by unknown authority","path":"root.input.processors.0","time":"2025-05-28T11:04:32Z"}`

**Processor Pipeline**:

```
  processors:
    - label: ""
      schema_registry_decode:
        url: "<self signed Schema URL>" 
        avro_raw_json: true
        tls:
          skip_cert_verify: false
          enable_renegotiation: false
          root_cas_file: /certs/ca.crt
          client_certs:
            - cert_file: /certs/cert.pem
              key_file: /certs/key.pem
              password: /certs/jks_passwords.txt
    - mapping: |
        root = this.dataGen.without("a","b")
```

This schema_registry_decode processor has started giving this issue once I migrated from jeffail image to Redpanda-connect latest image. I have followed this documentation as well https://docs.redpanda.com/redpanda-connect/components/processors/schema_registry_decode/ . But no configuration is helping out here. All the configured certs are present in the docker at the path specified.

Please suggest
