### ISSUE TITLE
Improve dynamic output multiplexing performance

### ISSUE THREAD

**Issue by Jeffail** [redpanda-data/connect#506]
The [`dynamic` output](https://www.benthos.dev/docs/components/outputs/dynamic) is currently the best performance option for dynamically altering the outputs of a stream. However, since this output is strictly fan-out, when the goal is to multiplex messages across the dynamic outputs we're forced to dispatch each message to every single output and rely on processors to filter down the correct messages:

```yaml
output:
  dynamic:
    outputs:
      foo:
        http_client: ...
        processors:
          - bloblang: root = if type != "a" { deleted() }
      bar:
        kafka: ...
        processors:
          - bloblang: root = if type != "a" { deleted() }
      baz:
        sqs: ...
        processors:
          - bloblang: root = if type != "b" { deleted() }
      ...
```

As the number of outputs increases the performance hit grows linearly, even when the number of outputs that a message dispatches to is static. Since this dynamic dispatch capability is pretty much unique to Benthos it would be cool to take this output one step further and offer a high performance multiplexing solution.

One possibility is to expand the current implementation to include a `check` field with each output so that the routing can be determined before dispatch. However, this still means executing a bloblang query for each output for each message, carrying an overhead per-output.

If we really want to eliminate a performance cost of having a large number of outputs then we need the check to be made once, and it returns a static list of outputs to be dispatched to. As an example we could implement behaviour whereby if a message has a metadata field `dynamic_output_dispatch` specified then we parse it as a comma separated list of outputs to dispatch to:

```yaml
pipeline:
  processors:
    - bloblang: |
        meta dynamic_output_dispatch = match type {
          case "a" => "foo",
          case "b" => "bar",
          case "c" => "baz",
          case "d" => "baz,buz",
        }
output:
  dynamic:
    outputs:
      foo:
        http_client: ...
      bar:
        kafka: ...
      baz:
        sqs: ...
      ...
```

Giving us a way to multiplex across a dynamic set of outputs with a single bloblang query.
