### ISSUE TITLE
Configuration templating

### ISSUE THREAD

**Issue by Jeffail** [redpanda-data/connect#590]
Benthos components are usually low level, where the preference is to give users the power to fully customize interactions such as http requests. However, there are lots of APIs and common patterns that we could help users access by providing a template around these lower level component configs that appears to be its own simpler component type.

If we were to implement this then it seems reasonable to allow users to write and import their own templates. Maybe one day we can even have an online ecosystem for sharing them.

Requirements:
  - templates appear like regular components with cli (`echo`, `generate`, `list`, etc)
  - templates can be mass produced and shipped with the binary (imagine lots of standard `http_client` inputs and outputs)
  - user defined templates can be imported (and verified) at runtime
  - templates override native components

Some thought needs to be made into how templates are defined. Bloblang seems like a great candidate but there are probably other more appropriate options out there. Some possible ideas:

Template defined using structured bloblang:

```yaml
name: foobar
type: input
summary: Allows you to pull foos from the foobar API.
fields:
  - name: thefoo
    type: string
    default: "foovalue"
  - name: thebar
    type: string

mapping: |
  root = {
    "http_client":
      "url": "http://example.com",
      "verb": "POST",
      "headers": {
        "something": "custom",
        "foo": this.thefoo,
        "bar": this.thebar,
      },
      "processors": [
        {
          "bloblang": """
            root = {
              "name": this.something.id,
              "content": this.body.content
            }
          """,
        },
      ]
    }
```

Template defined using string injected bloblang:

```yaml
name: foobar
type: input
summary: Allows you to pull foos from the foobar API.
fields:
  - name: thefoo
    type: string
    default: "foovalue"
  - name: thebar
    type: string

mapping: |
  root = """
  http_client:
    url: http://example.com
    verb: POST
    headers:
      something: custom
      foo: %v
      bar: %v
  processors:
    - bloblang: |
        root = {
          "name": this.something.id,
          "content": this.body.content
        }
  """.format(this.thefoo, this.thebar)
```

Template defined using golang template package:

```yaml
name: foobar
type: input
summary: Allows you to pull foos from the foobar API.
fields:
  - name: thefoo
    type: string
    default: "foovalue"
  - name: thebar
    type: string

template: |
  http_client:
    url: http://example.com
    verb: POST
    headers:
      something: custom
      foo: {{ index . "thefoo" }}
      bar: {{ index . "thebar" }}
  processors:
    - bloblang: |
        root = {
          "name": this.something.id,
          "content": this.body.content
        }
```

And you would instantiate it like this:

```yaml
input:
  foobar:
    thefoo: foome
    thebar: barme
```
