### ISSUE TITLE
Add request parsing options for http_server input

### ISSUE THREAD

**Issue by greysond** [redpanda-data/connect#766]
This enhancement would add some additional configuration to the `http_server` input like so:

```yaml
input:
  http_server:
    # ...
    request:
      headers:
        copy: true
        key_prefix: ""
        join_values: false
        value_separator: ""
      query_params:
        copy: true
        key_prefix: ""
        join_values: false
        value_separator: ""
      cookies:
        copy: true
        key_prefix: ""
```

The above are default values that preserve the current functionality.
