### ISSUE TITLE
`sftp` input with large file is generating multiple copies to the output

### ISSUE THREAD

**Issue by mfamador** [redpanda-data/connect#900]
Hi! 
I have this pipeline using the `sftp` input and the `azure_blob_storage` output.

```yaml
input:
  sftp:
    address: "127.0.0.1:2222"
    paths:
      - /file_*.csv
    codec: all-bytes

output:
  azure_blob_storage:
    storage_account: "mystorageaccount"
    container: "tests"
    path: ${!timestamp("2006-01-02")}/${!timestamp_unix_nano()}.csv
```

We only have one file in the sftp server (local docker container), but we've noticed that how bigger the file being download is the more "retries" we get, outputting the same file multiple times to the blob storage.

If we use the `file` input everything works as expected, just creates one output file.

Thanks!
