### ISSUE TITLE
Pulsar Component - missing features

### ISSUE THREAD

**Issue by crtomirmajer** [redpanda-data/connect#917]
Pulsar component is missing some important features:
- support for Token/OAuth2 Authentication, currently [none](https://github.com/Jeffail/benthos/blob/master/internal/impl/pulsar/input.go#L114-L118). I suggest adding the following:

```
pulsar:
    auth:
        oauth2:
          audience: "urn:sn:pulsar:x:y"
          issuer_url: "https://auth.xyz"
          private_key_file: /this/folder/key.json
        token:
          token: <base64-token-here> 
```

- configurable subscription type, currently hardcoded to [Shared](https://github.com/Jeffail/benthos/blob/master/internal/impl/pulsar/input.go#L125). My proposal is to add `subscription_type` option:
```
pulsar:
   subscription_type: <type-here>  # one of: shared, key_shared, exclusive, failover
```
- message attributes, such as `id`, `publishTime`, `redeliveryCount`, etc. (see [Message interface](https://github.com/apache/pulsar-client-go/blob/master/pulsar/message.go#L71-L123))
