### ISSUE TITLE
`split` batch is lost and regrouped if within a switch

### ISSUE THREAD

**Issue by mfamador** [redpanda-data/connect#986]
Hi.

I needed to limit the number of parts within a message reaching a particular output.
As advised, I've used successfully the `split` processor and with the following example, I'm receiving, as expected, multiple messages in the `stdout` output with 2 parts each.

```yaml
input:
  generate:
    count: 1
    mapping: |
      root = {
          "foo": "bar",
          "samples": [
            {"bar":"foo1"},
            {"bar":"foo2"},
            {"bar":"foo3"},
            {"bar":"foo4"},
            {"bar":"foo5"},
            {"bar":"foo6"},
            {"bar":"foo7"},
            {"bar":"foo8"},
            {"bar":"foo9"},
            {"bar":"foo10"},
            {"bar":"foo11"},
            {"bar":"foo12"}
        ]
      }

pipeline:
  processors:
  - bloblang: |
      root = this.explode("samples")
  - unarchive:
      format: json_array
  - split:
      size: 2
  - bloblang: |
      root = this.merge(this.samples.map_each_key(key -> key))
  - bloblang: |
      root = this
      samples = deleted()

output:
  stdout: { }
```

The issue is when I use the `split` processor within a `switch`, somehow the parts are regrouped back together again, and the output is now receiving 1 message with 12 parts again.

```yaml
input:
  generate:
    count: 1
    mapping: |
      root = {
          "foo": "bar",
          "samples": [
            {"bar":"foo1"},
            {"bar":"foo2"},
            {"bar":"foo3"},
            {"bar":"foo4"},
            {"bar":"foo5"},
            {"bar":"foo6"},
            {"bar":"foo7"},
            {"bar":"foo8"},
            {"bar":"foo9"},
            {"bar":"foo10"},
            {"bar":"foo11"},
            {"bar":"foo12"}
        ]
      }

pipeline:
  processors:
  - switch:
    - check: '!errored()'
      processors:
      - bloblang: |
          root = this.explode("samples")
      - unarchive:
          format: json_array
      - split:
          size: 2
      - bloblang: |
          root = this.merge(this.samples.map_each_key(key -> key))
      - bloblang: |
          root = this
          samples = deleted()

output:
  stdout: { }
```

I could use the `split` processor after the switch, or at the output level, but I feel this behaviour of the `split` inside a `switch` being "reverted", isn't what we would expect. 

Thanks!

**Comment by Jeffail** [comment]
Hey @mfamador, marking this as a documentation/configuration issue as ideally we need to be better at informing around this behaviour as it's not possible to honor split batches from within case processors. I had a look and we have a blurb right at the bottom of the page https://www.benthos.dev/docs/components/processors/switch#batching but given how critical it is it needs to moved to the top and ideally expanded with a solid example.

## Explanation

The reason we can't do this is because it's possible for a given message to match more than one case when specifying a `fallthrough`, which means two cases can execute a series of processors against two different sets of messages from the input batch.

We rearrange the messages that result from these processors back into the original order (when applicable) so that the output batch isn't disjointed from basic use. It wouldn't be possible to do the opposite of this, where instead we honor the batching and ordering resulting from case processors, because different cases might arrange individual messages into different groups.

An example might be this:

```yaml
pipeline:
  processors:
    - switch:
        - check: this.id % 3 == 0
          fallthrough: true
          processors:
            - group_by_value: ${! this.topic }
            - bloblang: '# do some windowed processing'

        - check: this.id % 2 == 0
          processors:
            - group_by_value: ${! this.key }
            - bloblang: '# do some windowed processing'
```

With the above config messages with an `id` that is divisible by both `2` and `3` will be grouped during case processing by `topic` and also by `key`. We can't support both in the resulting output so it wouldn't be possible to make sense of this other than to disregard the grouping (and splitting) of batches made within the case processors.

This does lead into the question of whether we should even allow batch-wise processing in these places since the changes are disregarded at the end. However, there are valid use cases where these processors might be useful within the individual case processing, so we can't disable them outright.

We could potentially provide linting errors instead. I've thought about this a fair amount and I think it'd be difficult to avoid false positives where we'd end up warning against legit usage.
